stan-dev/stanc3

lib/Errors.ml, lib/Errors.mli, lib/lexer.mll, test/integration/examples-bad/algebra_solver/stanc.expected, test/integration/examples-bad/compound-assign/stanc.expected, test/integration/examples-bad/data_index/stanc.expected, test/integration/examples-bad/for_loops/stanc.expected, test/integration/examples-bad/function-signatures/stanc.expected, test/integration/examples-bad/lang/stanc.expected, test/integration/examples-bad/map_rect/stanc.expected, test/integration/examples-bad/new/stanc.expected, test/integration/examples-bad/ode/adams/stanc.expected, test/integration/examples-bad/ode/stanc.expected, test/integration/examples-bad/reserved/stanc.expected, test/integration/examples-bad/stanc.expected, test/integration/examples-good/code-gen/pretty.expected, test/integration/examples-good/model/pretty.expected, test/integration/examples-good/pretty.expected, test/integration/included/dep-warning.stan, test/integration/included/incl_stanc_helper_deprecated_warning.stan, test/integration/included/stanc.expected, test/integration/included/stanc_helper_with_bad_include_deprecated_warning.stan, test/integration/model-name/stanc.expected, test/integration/rstanarm/data/pretty.expected, test/integration/rstanarm/functions/pretty.expected, test/integration/rstanarm/gqs/pretty.expected, test/integration/rstanarm/model/pretty.expected, test/integration/rstanarm/parameters/pretty.expected, test/integration/rstanarm/tdata/pretty.expected, test/integration/rstanarm/tparameters/pretty.expected
This should hopefully fix issue
https://github.com/stan-dev/stanc3/issues/7
=> Fixing include trace

lib/Semantic_check.ml, test/integration/examples-bad/bad_fundef_returntypes1.stan, test/integration/examples-bad/bad_fundef_returntypes2.stan, test/integration/examples-bad/bad_fundef_returntypes3.stan, test/integration/examples-bad/stanc.expected, test/integration/examples-good/good_fundef_returntypes1.stan, test/integration/examples-good/good_fundef_returntypes2.stan, test/integration/examples-good/good_fundef_returntypes3.stan, test/integration/examples-good/good_fundef_returntypes4.stan, test/integration/examples-good/pretty.expected
Slight refactoring to simplify semantic check.
I also added some extra test models.
=> Simplifying semantic check

lib/parser.messages, test/integration/examples-bad/new/stanc.expected, test/integration/examples-bad/stanc.expected
Not much really. Just some small fixes that I noticed.
=> Fixing some error messages

docker/dev-ubuntu/Dockerfile, docker/static/Dockerfile, lib/Ast_to_Mir.ml, lib/Mir.ml, lib/Stan_math_backend.ml, lib/Stan_math_code_gen.ml, lib/dune, scripts/install_build_deps.sh, scripts/install_dev_deps.sh, scripts/setup_dev_env.sh, stanc.ml
=> Switch to Fmt library (ready now)

lib/Dataflow_utils.ml, stanc.ml
Updated formatting, removed dead code
=> Formatting, dead code removal

lib/Expression_gen.ml, notes/function-name-generation.txt
This PR is practice for me to learn OCaml and also to help other devs understand how expression generation works.
It does *not* use the `Format` or `Fmt` libs.  It's just simple `sprintf` throughout.
I'd love to get feedback on how to do some of this better, like using sets rather than lists for the built-in functions that need `stan::math::` qualification.
=> [WIP] Expr gen practice

lib/Ast_to_Mir.ml, lib/Expression_gen.ml, lib/Mir.ml, lib/Stan_math_code_gen.ml, test/integration/examples-good/code-gen/cpp.expected
But still need to generate the correct type in the AST. Fixes the MIR half down for #79, renamed the issue to deal with the frontend half of the fix.
=> Add necessary information to Assignment in MIR

lib/Ast_to_Mir.ml, lib/Ast_to_Mir.mli, lib/Expression_gen.ml, lib/Mir.ml, lib/Stan_math_code_gen.ml
Curious what you all think about the results here. We seem to gain approximately nothing in code gen, it seems - we really can't construct functions that are unaware of at least the expression metadata for easier testing or anything. But curious if anyone can spot mistakes or anti-patterns here and has suggestions.
=> Double down on the parameterization of the MIR

Jenkinsfile
`dune runtest` should be run without `-x windows`.
=> Jenkins windows fix

Jenkinsfile
Move building of binaries to be in parallel. PRs were waiting on Mac and Windows machines just to be able to skip those steps, which is weird and probably a bug in Jenkins.
diff without whitespace changes: https://github.com/stan-dev/stanc3/pull/141/files?w=1
=> [Jenkins] parallel release builds

notes/working-models.txt, src/frontend/Ast_to_Mir.ml, src/middle/Mir.ml, src/stan_math_backend/Expression_gen.ml
Thanks for the pointer @syclik :)
=> Fix #63, which fixed low_dim_gauss_mix

src/middle/Stan_math_signatures.ml, test/integration/bad/propto-bad1.stan, test/integration/bad/stanc.expected, test/integration/good/pretty.expected, test/integration/good/propto-good.stan
This addresses issue https://github.com/stan-dev/stanc3/issues/63 .
=> Fixing semantic check to accept _propto distributions

Jenkinsfile
=> [Jenkins] See if we can graph our model coverage over time

src/frontend/Ast.ml, src/frontend/Ast_to_Mir.ml, src/frontend/Pretty_printing.ml, src/frontend/Semantic_check.ml, src/frontend/parser.mly
This fixes point 1. of issue https://github.com/stan-dev/stanc3/issues/112 . Moreover, it does a lot of DRYing.
I'd rather do point 2. in a separate PR as it's quite a different matter.
=> Fix fn kind 1

Jenkinsfile, notes/working-models.txt, src/stan_math_backend/Expression_gen.ml, src/stan_math_backend/Stan_math_code_gen.ml, src/stan_math_backend/Statement_gen.ml, test/integration/good/code-gen/cpp.expected
=> [codegen] Fix SIR stat_comp_benchmark model!

src/frontend/Semantic_check.ml
This fixes part 2 of issue https://github.com/stan-dev/stanc3/issues/112 .
=> Fixing bug in FunKind determination

src/frontend/Ast.ml, src/frontend/Ast_to_Mir.ml, src/frontend/Parse.ml, src/frontend/Pretty_printing.ml, src/frontend/Semantic_check.ml, src/frontend/parser.mly
This PR fixes issues https://github.com/stan-dev/stanc3/issues/79 and https://github.com/stan-dev/stanc3/issues/74 .
=> Add types to lhs

src/frontend/Ast_to_Mir.ml, test/integration/good/code-gen/cpp.expected
Important point: A Mir Single index into a matrix returns a matrix row.
That is all.
=> Fix litter.stan

src/stan_math_backend/Stan_math_code_gen.ml, test/integration/good/code-gen/cpp.expected
Fix for the indentation of try blocks in generated C++.
=> Fixing indentation

src/stan_math_backend/Expression_gen.ml, src/stan_math_backend/Stan_math_code_gen.ml, test/integration/good/code-gen/cpp.expected
Also, switched to emitting `rvalue` instead of `stan::model::rvalue`
=> Fix schools-3

src/frontend/Ast_to_Mir.ml, src/stan_math_backend/Stan_math_code_gen.ml, test/integration/good/code-gen/cpp.expected, test/unit/Optimize.ml
=> Start generating writes for transform_inits

src/stan_math_backend/Stan_math_code_gen.ml, src/stan_math_backend/Transform_Mir.ml, src/stan_math_backend/Transform_Mir.mli
Wish it was more of the codegen
=> Split out MIR transformations into separate file from the rest of codegen

src/stan_math_backend/Statement_gen.ml, src/stan_math_backend/Transform_Mir.ml
Separating out C++ generation and MIR-transformation more
=> Moving { } - wrap body to MIR-transformation

Jenkinsfile, docker/static/Dockerfile
Docker image is using UID 1000.
I had to replicate the groups permissions on the container and add UID 1000 to Jenkinsfile call.
UID 1004 and UID 1000 belong to the jenkins group on the host machine.
Now that permissions match, this should be avoided on the linux box.
It worked on EC2 Machines because ubuntu UID is 1000.
=> Fix gelmanlinux docker

src/stan_math_backend/Expression_gen.ml, src/stan_math_backend/Stan_math_code_gen.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/mother.stan, test/unit/Stan_math_code_gen_tests.ml
Ref #234  (Maybe fixes?) 
A lot of the stuff from the unit tests seemed to already be in the mother model, thanks to @mitzimorris!
=> Add more model behavior tests from stan2/src/test/unit/lang/generator

Jenkinsfile, src/frontend/Ast.ml, src/frontend/Ast_to_Mir.ml, src/frontend/Debug_data_generation.ml, src/frontend/Parse.ml, src/frontend/Pretty_printing.ml, src/frontend/Semantic_check.ml, src/frontend/parser.mly, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/mir.expected
This will be useful for two things:
1) eventually allowing unsized local variables
2) during desugaring generating new declarations that it seems impossible to determine the sizes of in general
=> Switch AST to possiblysized variable declaration types

src/stan_math_backend/Expression_gen.ml
Fix the 3 examples from [Andre Pfeuffer on Discourse](https://discourse.mc-stan.org/t/first-stanc3-release-candidate/9692/6). Thanks!
=> Fix some example breakages from Andre Pfeuffer

src/middle/Stan_math_signatures.ml, test/integration/good/function-signatures/math/functions/integrate_1d.stan, test/integration/good/function-signatures/math/functions/pretty.expected, test/integration/signatures/stan_math_sigs.expected
Also fixes stan-dev/stan/#2786
=> Fixes #301 - add sigs for integrate_1d.

src/stan_math_backend/Expression_gen.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected
We may eventually want to line this up with the Stan code indicated by the location span instead.
=> Fixes #239 by using the MIR pretty printer.

src/stan_math_backend/Expression_gen.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/mir.expected, test/integration/good/code-gen/mother.stan
@rybern this should fix what you found in test/integration/good. I'll test the rest of the models too to make sure they compile. Thanks!
=> Fix compilation of special hof function argument orders

src/stan_math_backend/Locations.ml, src/stan_math_backend/Stan_math_code_gen.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected, test/unit/Stan_math_code_gen_tests.ml
Also removes error messages and rethrows original exception which preserves it's type which is important for some Stan sampling code that relies on the type of exception to do different things.
=> Fix location numbers - off by one error.

src/middle/Location.ml, src/middle/dune, src/stancjs/stancjs.ml
=> Updates required to get JS to build again after refactor

Jenkinsfile, src/stan_math_backend/Stan_math_code_gen.ml, test/integration/good/code-gen/cl.expected, test/integration/good/code-gen/cpp.expected
=> Add var context data validation for missing data

src/stanc/stanc.ml
=> Turn on optimization of adlevels by default.

src/frontend/parser.mly, src/stan_math_backend/Expression_gen.ml, test/integration/bad/matrix_expr_bad5.stan, test/integration/bad/row_vector_expr_bad3.stan, test/integration/bad/stanc.expected, test/integration/good/vec-expr/matrix_expr_terms.stan, test/integration/good/vec-expr/pretty.expected, test/integration/good/vec-expr/row_vector_expr_terms.stan
=> size zero row vector expressions

src/stan_math_backend/Cpp_Json.ml
Issue #404
By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
* Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
* Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)
=> improve Cpp_Json

src/stan_math_backend/Transform_Mir.ml, test/integration/good/code-gen/cl.expected, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/optimize_glm.stan
Allows transformed data that is passed to an opencl capable function to be cached on the GPU
Licensed under BSD3
Do we need additional tests for this? Could add the brms model from #423
=> OpenCL can now also use transformed parameters

src/stan_math_backend/Expression_gen.ml, src/stan_math_backend/Stan_math_code_gen.ml, src/stan_math_backend/Transform_Mir.ml, test/integration/good/code-gen/cl.expected, test/integration/good/code-gen/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected
=> bugfix 387 move context__.vals_r() calls out of for-loops

Jenkinsfile
I am currently going through all the Jenkins files/jobs to document them and saw this Jenkinsfile a bit messy.
This PR only touches that by pretty formatting it for ease of readability.
=> Pretty formatted Jenkinsfile

src/stanc/stanc.ml
=> Add 3 to version number

src/stan_math_backend/Transform_Mir.ml, test/integration/good/code-gen/cl.expected, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/optimize_glm.stan
=> Use matrix_cl overloaded math signatures for GLMs with tilde

src/frontend/lexer.mll, test/integration/included/included-brackets.stan, test/integration/included/stanc.expected
=> Added specifying include files with < > brackets in addition to quotes

src/frontend/Parse.ml, src/frontend/parser.messages, src/frontend/parser.mly, test/integration/bad/new/stanc.expected, test/integration/good/pretty.expected, test/integration/good/validate_set_double_offset_multiplier_good.stan, test/integration/good/validate_set_double_range_lower_good.stan
Also added complete error messages.
Addresses #511
=> Added reverse-ordered offset/multiplier and lower/upper to the parser

src/frontend/Ast_to_Mir.ml, src/stan_math_backend/Transform_Mir.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/mir.expected, test/integration/good/compiler-optimizations/cpp.expected, test/unit/Optimize.ml
=> fix transform_inits for constrained types

src/frontend/Ast_to_Mir.ml, src/middle/Stmt.ml, src/middle/Stmt.mli, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/mir.expected, test/integration/good/code-gen/mother.stan
=> For-each sliced arrays fix

src/frontend/Ast_to_Mir.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/mir.expected, test/integration/good/compiler-optimizations/cpp.expected, test/unit/Optimize.ml
https://github.com/stan-dev/stanc3/issues/485#issuecomment-615250724
=> sized decls for unconstrained params

src/stan_math_backend/Statement_gen.ml, test/integration/good/code-gen/cl.expected, test/integration/good/code-gen/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected
=> Change the type of loop indices from size_t to int

README.md, default.nix, src/middle/Stan_math_signatures.ml
Getting the environment set up for Stanc3 with Opam seems to be a pain point for some would-be developers. I'm publishing the Nix expression that I use in case that's an easier alternative for anyone. See the README update for a short explanation of Nix usage.
=> Add Nix expression and README section on Nix usage

README.md
Fixed some formatting and wording issues in the Nix section of the readme.
Sorry for the extra PR, I should have checked the rendering when I submitted the Nix PR.
=> Improved formatting of README Nix build instructions

Jenkinsfile
Update Jenkins to a newer version of tfp-nightly
=> update tfp-nightly version

src/stan_math_backend/Stan_math_code_gen.ml, test/integration/good/code-gen/cl.expected, test/integration/good/code-gen/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected
=> Emit current_statement__ before context__.validate_dims()

src/middle/SizedType.ml, src/middle/Stmt.ml, src/stan_math_backend/Transform_Mir.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected
I think this should fix issue #609
Pretty sure indexing in `unconstrained_param_names()` is also broken but [a comment](https://github.com/stan-dev/stanc3/blob/5de57e01f7e070b745696307aacfe229d4774958/src/stan_math_backend/Stan_math_code_gen.ml#L505-L507) says it's probably always been broken in other ways too.
=> fix indexing in transform_init

src/tfp_backend/Code_gen.ml, test/integration/tfp/tfp_models/nested_expr.py
Change power op string from Stan's ^ to Python's **
=> fix python power op string

src/stan_math_backend/Expression_gen.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected
This PR reverts #521 
There is nothing wrong with the stanc3 implementation itself, but rvalue seems to does have a performance penalty the way it is implemented right now. I will dig a bit more in the rvalue implementation if we can maybe not revert the stanc3 PR. If we can't find a solution, it will have to be reverted for the release.
=> Revert 521

src/frontend/parser.mly, test/integration/good/pretty.expected, test/integration/good/single-arg-conddist.stan
Fixes #720 
No release notes as this PR is fixing a bug for a feature that has not been released yet. 
=> Fix single-arg unnormalized parsing

src/frontend/Semantic_check.ml, src/frontend/Semantic_error.ml, src/frontend/Semantic_error.mli, src/stan_math_backend/Expression_gen.ml, src/stan_math_backend/Stan_math_code_gen.ml, test/integration/bad/unnormalized/lupdf_ident.stan, test/integration/bad/unnormalized/lupdf_in_gq_rs.stan, test/integration/bad/unnormalized/lupdf_in_trans_params_rs.stan, test/integration/bad/unnormalized/stanc.expected, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/reduce_sum_m1.stan
=> Fix for reduce_sum with lupdf

src/stan_math_backend/Expression_gen.ml, test/integration/good/code-gen/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected
Fix #578 
Use Eigen comma initializer to avoid copy in vector construction.
=> Eigen comma initializer for FnMakeRowVec

src/middle/Stan_math_signatures.ml, test/integration/good/ode/ode_ckrk_test_model.stan, test/integration/good/ode/ode_ckrk_tol_test_model.stan, test/integration/good/ode/pretty.expected
Fixes #826 
Added ode_ckrk and ode_ckrk_tol to the Stan language.
=> Add ode_ckrk and ode_ckrk_tol

Jenkinsfile
Build ARM binaries only on releases
=> Build ARM binaries only on releases

src/frontend/Parse.ml, src/middle/Errors.ml, src/middle/Errors.mli, test/integration/cli-args/dune, test/integration/cli-args/notfound.expected
=> Error for compiling non-existent file

src/stanc/stanc.ml
Add missing space in help text.
Metrum Research Group.
=> Add missing space in help

Jenkinsfile
We have been experiencing some issues with tests, mostly as issues with PCH files. Opening a PR to debug and find a solution.
=> Fix Jenkins tests

Jenkinsfile
Removes dune runtest from binary build stage
=> Remove dune runtest from binary build stage

src/stan_math_backend/Stan_math_code_gen.ml, test/integration/cli-args/filename_good.expected, test/integration/good/code-gen/cl.expected, test/integration/good/code-gen/cpp.expected, test/integration/good/code-gen/expressions/cpp.expected, test/integration/good/code-gen/ode/cpp.expected, test/integration/good/code-gen/opencl/cpp.expected, test/integration/good/code-gen/profiling/cpp.expected, test/integration/good/compiler-optimizations/cpp.expected
Quick fix for https://github.com/stan-dev/httpstan/issues/577. Wanted to run the tests on this to make sure it's fine but let me add one more quick check before we merge. Should be ready by tmrw  afternoon (EST time) @rok-cesnovar I'll ping you when I post it.
=> update transform_inits to only look for parameter names in unserialization

Jenkinsfile
Making sure we're removing hidden files in odoc job.
=> Make sure we're removing hidden files

src/analysis_and_optimization/Factor_graph.ml, src/frontend/Ast_to_Mir.ml, src/frontend/Debug_data_generation.ml, src/frontend/Errors.ml, src/frontend/Info.ml, src/frontend/Pretty_printing.ml, src/frontend/Semantic_error.ml, src/frontend/SignatureMismatch.ml, src/frontend/Typechecker.ml, src/middle/Expr.ml, src/middle/Internal_fun.ml, src/middle/SizedType.ml, src/middle/Stan_math_signatures.ml, src/stan_math_backend/Cpp_Json.ml, src/stan_math_backend/Expression_gen.ml, src/stan_math_backend/Stan_math_code_gen.ml, src/stan_math_backend/Statement_gen.ml, src/stanc/stanc.ml, src/stancjs/stancjs.ml, src/tfp_backend/Code_gen.ml, test/unit/Ast_to_Mir_tests.ml, test/unit/Desugar_test.ml, test/unit/Optimize.ml, test/unit/Pedantic_analysis.ml, test/unit/Semantic_check_tests.ml, test/unit/Stan_math_code_gen_tests.ml
Prepare the code for newer version of the `Fmt` library.
=> Make code compatible with Fmt 0.9

Jenkinsfile
Using the libraries from @serban-nicusor-toptal.
=> Add ways to specify cmdstan, stan and math PR branches

Jenkinsfile
Fix a Jenkinsfile conditional to also take in consideration when we're not building the binaries.
=> Do not release binaries when we're not building them.

docs/getting_started.mld
Closes #1077 
Update developer getting started docs
=> Update getting started docs

src/middle/Stan_math_signatures.ml, test/integration/good/function-signatures/distributions/univariate/continuous/normal/normal_id_glm.stan, test/integration/good/function-signatures/distributions/univariate/continuous/normal/pretty.expected, test/integration/signatures/stan_math_signatures.t
Added additional `normal_id_glm` signatures.
=> Add missing normal_id_glm signatures

src/middle/Stan_math_signatures.ml
Turns on SoA matrices for glm lpdf functions
=> update glm signatures to accept SoA matrices

src/frontend/Pretty_printing.ml, test/integration/cli-args/canonicalize/include/stanc.expected, test/integration/downstream/rstanarm/pretty.expected
Closes #1103. @rok-cesnovar - we could merge this during the freeze IMO since its only cosmetic 
Format #includes without `<` and `>`
=> Remove <> from pretty-printing includes

src/frontend/Preprocessor.ml, src/frontend/Typechecker.ml, src/stan_math_backend/Stan_math_code_gen.ml, src/stancjs/stancjs.ml, test/stancjs/stancjs.expected, test/stancjs/warnings.js
Closes #1117 
Clean up more mutable state in the Javascript interface
=> Clear more mutable state in stancjs

Jenkinsfile
=> Fixed branch config in CI, fixed when

Jenkinsfile-test-binaries
Refactored Jenkinsfile-test-binaries for Flatiron Jenkins Instance.
Test pipeline: https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2Fstanc3-test-binaries/detail/stanc3-test-binaries/5/pipeline
=> Refactored Jenkinsfile-test-binaries for Flatiron instance

Jenkinsfile
Updated `verifyChanges` function call to merge with master when verifying changes after the change in [jenkins-shared-libraries](https://github.com/stan-dev/jenkins-shared-libraries/pull/5).
=> Update Jenkinsfile verifyChanges function call

src/middle/Stan_math_signatures.ml
Adds `cumulative_sum(Vector/RowVector)` for `var<Matrix>` types
=> adds cumulative sum for varmat

src/middle/Stan_math_signatures.ml, test/integration/good/function-signatures/math/matrix/eigenvalues.stan, test/integration/good/function-signatures/math/matrix/eigenvectors.stan, test/integration/signatures/stan_math_signatures.t
Added `eigenvectors` and `eigenvalues` functions which return the complex-valued eigenvectors or eigenvalues of a real (asymmetrix) matrix.
=> Expose eigenvectors and eigenvalues functions for real matrices

.github/workflows/binaries.yml, scripts/install_build_deps_windows.sh, stanc.opam
Closes #1160 
This uses https://github.com/ocaml/setup-ocaml to simplify the github action script. This handles opam setup and caching.
See sample run [here](https://github.com/stan-dev/stanc3/runs/6375886206)
=> Rewrite "Build Binaries" github action

src/analysis_and_optimization/Pedantic_dist_warnings.ml, src/middle/Stan_math_signatures.ml, test/integration/good/function-signatures/distributions/multivariate/continuous/wishart_cholesky_lpdf.stan, test/integration/good/function-signatures/distributions/rngs.stan, test/integration/signatures/stan_math_distributions.t, test/integration/signatures/stan_math_signatures.t
Adds `wishart_cholesky_lpdf` and `wishart_cholesky_rng`.
Added `wishart_cholesky_lpdf` and `wishart_cholesky_rng` distribution functions.
=> wishart_cholesky signatures

Jenkinsfile
Make sure we're not running expression tests when other stages are skipped(building).
=> Fix expression tests conditional in CI

src/middle/Stan_math_signatures.ml, test/integration/good/function-signatures/math/functions/norm1.stan, test/integration/good/function-signatures/math/functions/norm2.stan, test/integration/signatures/stan_math_signatures.t
L1 and L2 norms.
By submitting this pull request, the copyright holder is agreeing to  Metrum Research Gruop.
=> expose norm1 & norm2

RELEASE-NOTES.txt
=> Added release notes into master

src/frontend/parser.messages, test/integration/bad/lang/bad_decl3.stan, test/integration/bad/lang/stanc.expected, test/integration/bad/stanc.expected
Closes #1238 
Improve error message for bad multiple declarations
=> Change parser message for junk after comma in decls

Jenkinsfile
Build binaries in parallel on Jenkins.
=> [WIP] [CI] Build binaries in parallel

Jenkinsfile
Fixes an issue with 'dune subst' in CI, see https://github.com/stan-dev/stanc3/issues/1250
=> Fix dune subst calls in CI

Jenkinsfile
=> Ensure tags are checked out when building Stanc3Setup

Jenkinsfile
[CI] A small issue where the files on disk are not cleaned up after ocaml testing stages has been found and fixed with this PR.
Thanks @WardBrian for reporting it.
=> Run ocaml tests in isolated dirs, ensure proper stage cleanup

Jenkinsfile
Set the correct repository owner username in ghr call. ( https://github.com/tcnksm/ghr/issues/86 )
Run pipeline on Jenkinsfile changes.
=> [CI] Set the correct repository owner username in ghr call 

Jenkinsfile
Because we do not clean after `VerifyChanges` master is keeping an older state on disk, this PR fixes this behavior.
=> Ensure proper cleanup during CI stage

RELEASE-NOTES.txt
Merge release/v2.33.1 release notes
=> Merge release/v2.33.1 release notes

src/middle/Stan_math_signatures.ml, test/integration/good/function-signatures/distributions/univariate/discrete/binomial/binomial_logit_glm.stan, test/integration/signatures/stan_math_distributions.t, test/integration/signatures/stan_math_signatures.t
Signatures and tests added for `binomial_logit_glm` distribution
=> Add signatures for binomial_logit_glm dist

Jenkinsfile
=> Make sure to pull code for odoc step so it can find Dockerfile

Jenkinsfile, scripts/docker/publish/Dockerfile
Create and build publish image under the same permissions for unstash to work properly.
=> Fix permission issue in CI

Jenkinsfile, scripts/docker/publish/Dockerfile
=> Ci fix permissions for publish

Jenkinsfile, scripts/docker/publish/Dockerfile
CI fix permissions for Release Binaries
=> CI fix permissions for Release Binaries

Jenkinsfile, scripts/docker/publish/Dockerfile
=> Fix publish binaries in CI

.github/workflows/binaries.yml
For issue #1391.
- [-] If a user-facing facing change was made, the documentation PR is here: <LINK>
Add `--profile static` to linux build step in github workflow.
By submitting this pull request, the copyright holder is agreeing to @yizhang-yiz .
=> build linux binary with static profile

docs/dependencies.mld, docs/getting_started.mld, src/frontend/Typechecker.mli
This is as much for me, as I semi-regularly need to look this stuff up.
Added more documentation for stanc3 developers on advanced topics: test coverage, fuzzing, and profiling.
=> Add more dev doc

Jenkinsfile, scripts/build_multiarch_stanc3.sh
Fix CI reply functionality by removing the use of unstash for binaries builds. Made steps optional by adding additional params.
=> Fix ci reply

src/analysis_and_optimization/Pedantic_analysis.ml, src/frontend/Semantic_error.ml, src/frontend/Semantic_error.mli, src/frontend/Typechecker.ml, test/integration/bad/stanc.expected, test/integration/cli-args/warn-pedantic/stanc.expected
Rename `sampling statement (~)` to `distribution statement (~)` to be consistent with the docs changes in https://github.com/stan-dev/docs/pull/777
=> Rename sampling statement to distribution statement

test/integration/good/comments.stan, test/integration/good/pretty.expected
=>  Add regression test for unicode in comment lines 

RELEASE-NOTES.txt
Add release notes for release v2.36.0
=> Release v2.36.0 - Add release notes

Jenkinsfile, scripts/docker/debian/Dockerfile, src/stanc/CLI.ml
=> Bump Node version in CI image

Jenkinsfile, Jenkinsfile-test-binaries
=> Make macos easier to change switches

Jenkinsfile, Jenkinsfile-test-binaries, test/integration/good/compiler-optimizations/ad-level-deep-dependence.stan
Cleans up some Groovy warnings 
=> Clean up Jenkinsfile interpolation
