stan-dev/stanc3

Jenkinsfile
lib/Semantic_check.ml

* Remove global variable `context_flags` from `Semantic_check.ml`
* Plumb immutable `context_flags` through as argument
* Use [functional updates](http://dev.realworldocaml.org/records.html#functional-updates) in place of mutability
No behavior changes, but this touches a lot of lines of code.

context_flags immutable with functional updates

---

lib/Semantic_check.ml

I changed the monadic notation in the semantic check to plain `Option.map`, as I think that's easier to Google and more self-explanatory than the infix operator `>>|`.

Removing monadic notation

---

test/integration/run_bin_on_args.ml

This PR makes sure that the integration tests can be run on Windows as well. It leads to the following behaviour:
- `dune runtest` will try to run the integration tests with the binary built in the `default.windows` context, if it exists;
- if not, then it simply uses the binary in the `default` context.
That is, on OSX / Linux, your workflow will stay the same and on WSL it will be such that
- `make clean`;  `dune runtest` will build an Ubuntu binary and run the tests on it;
- `make clean`; `dune build -x windows @runtest` will build a Windows binary and run the tests on it.

Fix integration tests to run on Windows too

---

lib/Errors.ml
lib/Errors.mli

The point is that this is useful to get nice error strings for the runtime errors as well, so the code gen needs to be able to see the method.

This exposes a method for rendering a location span as a pretty string for errors.

---

lib/Mir.ml
lib/Monotone_framework.ml
lib/Monotone_framework_sigs.mli
lib/Optimize.ml
lib/Partial_evaluator.ml

This implements the monotone framework, as described in 2.3-2.4 of
Nielson, Nielson, and Hankin or 9.3 of Aho et al..
This gives a modular way of implementing many static analyses.
We give nine different instances of the framework:
- constant propagation/folding [used for constant propagation optimization]
- expression propagation/folding (aka forward substitution)  [used for forward substitution optimization]
- copy propagation [used for copy propagation optimization]
- reaching definitions [used for e.g. dependence analysis]
- live variables [used for dead code elimination optimization]
- anticipated expressions [used for lazy code motion optimization]
- available expressions [used for lazy code motion optimization]
- postponable expressions [used for lazy code motion optimization]
- …

Monotone framework

---

lib/Ast.ml
lib/Ast_to_Mir.ml
lib/Operators.ml
lib/Operators.mli
lib/Parse.ml
lib/Pretty_printing.ml
lib/Semantic_check.ml
lib/parser.mly

The PR https://github.com/stan-dev/stanc3/pull/73 introduced a bug in the treatment of prefix operators, causing prefix (unary) minus and plus to be translated into the Mir as binary minus and plus. The PR fixes that bug. There is a unit test included which was failing before this PR, which checks that the prefix minus gets translated to the MIR correctly.

Prefix operator fix

---

lib/Mir.ml

Adding a pretty printer for MIR. There are a couple of choices I made which need review:
~~1.`pp_io_var` adds the name of the `io_block` in double angle brackets after the declaration e.g. `int x <<data>>;`~~
1. `pp_io_var` now pretty prints the `io_block` before the declaration in line with @bob-carpenter 's proposal [here](https://discourse.mc-stan.org/t/generalizing-the-stan-language-for-stan-3/1599?source_topic_id=1781) and SlicStan
2. `pp_index` represents a `MultiIndex` with a tilde (`~`) followed by the index expression

MIR Pretty Printer

---

.gitignore

Using and opam switch creates directory named `_opam` which should be ignored by git.

Add `_opam` to git ignore.

---

lib/Ast_to_Mir.ml
lib/Mir.ml
lib/Stan_math_code_gen.ml

Pulled out fun_defs, so that they can only appear in the functions_block of a prog. Currently throwing an error if AST FunDefs appear anywhere outside of the function block, or if there are any non-FunDefs in the function block.
This is a new version of PR https://github.com/stan-dev/stanc3/pull/92 to address issue https://github.com/stan-dev/stanc3/issues/78. I started over since there have been many changes to master.

Extract fun_defs into their own type

---

src/frontend/Ast_to_Mir.ml

The function body of a forward declaration is Skip, not a Block.

Bug fix for code gen for forward declared functions (e.g. recursive functions)

---

src/middle/Middle.ml

This PR fixes #116; previously `if`, `for`, `foreach` and `while` statements always printed contained statements in curly braces whilst block did not indicate any scoping was happening. The PR reverses that so that braces are only printed if the body of one the statements is a block and blocks are printed with braces outside of those statements.

Fix MIR pretty printing bugs (#116)

---

src/frontend/Semantic_check.ml

During semantic checking of blocks, we drop statements after an escape statement when determining the return type but all statements should have bee included in the semantically checked block but only those used in determining return type were.

Fix #142 - statements `dropped in semantic_check_block` 

---

src/frontend/Ast_to_Mir.ml
src/middle/Middle.ml
src/middle/Middle.mli
src/stan_math_backend/Expression_gen.ml
src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/code-gen/cpp.expected

Turns out using declarations to immediately generate checks doesn't work - you need to move the checks to the end of their respective blocks because they may be assigning the variables (and modifying them) at arbitrary locations in the block, and they need to be checked after that.

Fix hepatitisME model

---

src/middle/Stan_math_signatures.ml
test/integration/bad/algebra_solver/stanc.expected
test/integration/bad/compound-assign/stanc.expected
test/integration/bad/lang/stanc.expected
test/integration/bad/ode/adams/stanc.expected
test/integration/bad/ode/stanc.expected
test/integration/bad/stanc.expected

This means the error messages won't change when the implementation of the signatures dictionary
changes. We also probably shouldn't rely on the ordering in the multi hash table, but not sure.

Sort type signatures in output.

---

src/analysis_and_optimization/Dependence_analysis.ml
test/unit/Dependence_analysis.ml

Fixed issue with parameters not being included correctly in the scope of the model or generated quantities blocks. See changed test case.

Small fix to warn-uninitialized

---

src/analysis_and_optimization/Dependence_analysis.ml
src/frontend/Ast.ml
src/frontend/Ast_to_Mir.ml
src/frontend/Pretty_printing.ml
src/middle/Mir.ml
src/middle/Mir_pretty_printer.ml
src/stan_math_backend/Transform_Mir.ml
test/integration/good/code-gen/mir.expected

We need this so that we can allow the Stan C++ model to expose this metadata (ref: https://discourse.mc-stan.org/t/interface-roadmap-last-draft-before-ratification-vote/10955/10)
Also helps with TFP backend - better to compile these to TFP bijectors than to imperative numerical code accomplishing hopefully the same thing.

Move transformations (bijectors) to MIR and include in Mir.prog.

---

src/stan_math_backend/Expression_gen.ml
src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/code-gen/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected

* remove the first argument from calls to map_rect even though all other HOFs have the first argument as the function and don't require explicit template arguments
* add a call_id integer that just increments every time we emit a call to map_rect. I think this was a hack that went in before because we didn't want to modify the old compiler too much; now I'm reproducing that hack in the new compiler in lieu of fixing it because it would require nontrivial changes to Math.

Fix map_rect

---

src/middle/Middle.ml
src/middle/Middle.mli
test/integration/bad/stanc.expected
test/unit/Ast_to_Mir_tests.ml
test/unit/Dataflow_utils.ml
test/unit/Factor_graph.ml

At the moment `sexp_of_expr_typed_located` and `sexp_of_stmt_loc` are both defined twice, once by the deriving annotation on the type definition and then, again, in `Middle.ml`. Since the implementations are different the pretty printed s-expression of the type differs depending on whether the implementations in `Middle.ml` are in scope.
This PR removes the second definition so we have consistent s-expressions and updates tests to this format.

Remove second scoped definition of `sexp_of_expr_typed_located` and `sexp_of_stmt_loc`

---

src/middle/Mir.ml
src/stan_math_backend/Expression_gen.ml
src/stan_math_backend/Stan_math_code_gen.ml
src/stan_math_backend/Transform_Mir.ml
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/mir.expected
test/integration/good/code-gen/mother.stan
test/integration/good/compiler-optimizations/cpp.expected

Fixes #340 and fixes #339. Adds a map_rect example to the mother model, because it is a very special function indeed.
We weren't initializing variables in a few places. Also added the calls to STAN_MAP_RECT_REGISTER.

Fix Ben's map_rect example model

---

src/frontend/Ast_to_Mir.ml
src/frontend/Semantic_check.ml
src/frontend/Semantic_error.ml
src/frontend/Semantic_error.mli
src/middle/Middle.ml
src/middle/Middle.mli
src/stan_math_backend/Stan_math_code_gen.ml
src/stan_math_backend/Transform_Mir.ml
test/integration/bad/stanc.expected
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/mir.expected
test/integration/good/compiler-optimizations/cpp.expected
test/unit/Stan_math_code_gen_tests.ml

Assumes we'll never want to autodiff something declared as an integer, which might make sense. I wasn't able to see a decent quick way of enabling autodiff over ints while preserving the old behavior. Also doesn't fill ints with NaN now. 
Fixes #343

Deal with ints the same way Stan 2 does in function signatures

---

test/integration/tfp/stan.py

NUTS expects initial values to be in the constrained space; passing random(0,2) returns nans for constrained variables outside of this range (for example, <upper=0>).

Using bijectors to constrain initial values

---

src/frontend/Canonicalize.ml
src/stanc/stanc.ml
test/integration/canonicalize/canonical.expected
test/integration/canonicalize/deprecated.stan
test/integration/canonicalize/dune
test/integration/canonicalize/parenthesize.stan

Based on issue #262.
A new command line option that removes deprecated syntax from Stan code and pretty prints the result. No attempt is made to infer priors.
I still need to figure out what tests are required. The pretty printer seems to have nothing but a `pretty.expected` file in every subdirectory of `test/integration/good`. How are those generated?

Stan code canonicalizer

---

src/stan_math_backend/Expression_gen.ml
src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/code-gen/cpp.expected

A quick fix for issue #335
See my comment on the issue for reasons why I chose this approach rather than the one suggested by the issue title.

remove  lp__ argument from _lpmf functions

---

src/tfp_backend/Code_gen.ml
test/integration/tfp/test_empty_data_block.stan

At the moment, a Stan program without a data block creates an empty `__init__` function which raises an indentation error in `def log_prob_one_chain`. This adds a simple `pass;` statement to avoid this.

added support for empty datablock

---

src/tfp_backend/Code_gen.ml
test/integration/tfp/dune
test/integration/tfp/eight_schools.py
test/integration/tfp/nested_expr.py
test/integration/tfp/nested_expr.stan
test/integration/tfp/normal_lub.py

TFP backend generates code with binary ops but when nested they need parenthesis to ensure the correct order of operations. This PR adds parens to all nested binary ops.

Fix parenthesis in TFP code gen

---

.gitignore

This adds the following patterns to `.gitignore`:
- `.DS_Store`
- `*~` 
- `\#*#`
and reorganizes it a bit.
I don't know if the convention here is to open an issue for each PR, given the triviality of this I'm sending this PR directly.

Organize .gitignore and add a few more patterns to ignore

---

src/stan_math_backend/Transform_Mir.ml
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/optimize_glm.stan

Now that the broadcast GLMs are added we need to refactor the conditions. This was discussed in the [original PR](https://github.com/stan-dev/stanc3/pull/314) that added GPU GLMs. Quoting @t4c1:
> Once signatures with broadcasting are added to remaining GLMs they will either go into "Use opencl if X (second argument - the matrix) is already on GPU." if X is a matrix or "Never use opencl." if x is a row_vector.
So this does just that. Basically all GLMs have the same condition of when to switch to using OpenCL: second argument is a data matrix

Refactor GPU GLM conditions

---

src/frontend/Semantic_check.ml
src/frontend/Semantic_error.ml
src/middle/UnsizedType.ml
test/integration/bad/stanc.expected

Copy Stanc2 error messages for ill-typed ternary operator `? :` expression.

improve ternary-if typechecking

---

Jenkinsfile-test-binaries

Adds a Jenkinsfile which will be used in the [test-binaries](https://jenkins.mc-stan.org/job/stanc3-test-binaries/) Jenkins job to build stanc3 binaries on-demand as requested in https://github.com/stan-dev/stanc3/pull/434

Jenkinsfile test binaries

---

src/stanc/stanc.ml
test/integration/bad/1_starts_with_number.stan
test/integration/bad/stanc.expected

Fixes #506 by outputing the following error message:
```
Model name must not start with a number or symbol other than underscore.
```
Entire cmdstan is then:
```
make examples/eight_schools/8schools
--- Translating Stan model to C++ code ---
bin/stanc  --o=examples/eight_schools/8schools.hpp examples/eight_schools/8schools.stan
Model name must not start with a number or symbol other than underscore.
make: *** No rule to make target 'examples/eight_schools/8schools.hpp', needed by 'examples/eight_schools/8schools'.  Stop.
```

Error on model name that starts with a number or non-underscore symbol

---

src/stan_math_backend/Expression_gen.ml
test/integration/good/code-gen/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected

Fixes #489 by forcing the use of `stan::model::rvalue()` instead of direct access. As far as I know that doesn't incur any performance penalty beyond the range check.
The range check is still skipped for compiler generated indexing as those are likely to be correct.

Check for out-of-bounds array access

---

src/frontend/Ast_to_Mir.ml
src/middle/Stan_math_signatures.ml
src/middle/Utils.ml
src/stan_math_backend/Transform_Mir.ml
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/mir.expected
test/integration/good/compiler-optimizations/cpp.expected
test/unit/Factor_graph.ml

Fixes #563 
Uses _lpdf or _lpmf instead of _log in tilde statements. See issue for examples.
The suffices were listed as 
```ocaml
["_log"; "_lpmf"; "_lpdf"]
```
and stanc3 used the first one that existed. So for `y ~ normal` it basically looked for `normal_log`, `normal_lpmf` and `normal_lpdf`, then filtered the ones that actually exists and took the first one.
Changed the suffices list to 
```ocaml
["_lpmf"; "_lpdf"; "_log"]
```
and that is it. The rest changes are just for tests.

use _lpdf/_lpmf rather than _log

---

src/analysis_and_optimization/Partial_evaluator.ml
src/frontend/Pretty_printing.ml
src/frontend/Semantic_check.ml
src/frontend/lexer.mll
src/frontend/parser.mly
src/middle/Operator.ml
src/middle/Stan_math_signatures.ml
src/stan_math_backend/Expression_gen.ml
src/tfp_backend/Code_gen.ml
test/integration/bad/op_intdivide_bad.stan
test/integration/bad/op_intdivide_bad_1.stan
test/integration/bad/op_intdivide_bad_2.stan
test/integration/bad/op_intdivide_bad_3.stan
test/integration/bad/stanc.expected
test/integration/example-models/bugs_examples/vol1/equiv/pretty.expected
test/integration/good/function-signatures/math/functions/operators_int.stan
test/integration/good/function-signatures/math/functions/operators_real.stan
test/integration/good/function-signatures/math/functions/pretty.expected
test/integration/good/pretty.expected
test/integration/good/validate_int_divide_good.stan
test/unit/Optimize.ml

Fix #533 
Adds new operator `%/%` for integer division that rounds toward zero. The warning the ordinary division operator emits when applied to integers is now more informative.
The `IntDivide` operator is not implemented in the Stan Math Library  as such a function would be redundant in C++. Instead the compiler special-cases the operator when type-checking and turns it into an ordinary division in the backend.

integer division operator

---

src/frontend/parser.mly
test/integration/good/pretty.expected
test/integration/good/single-arg-conddist.stan

Fix #393
Change the parser to recognize single-argument `_lpdf` calls as CondDistApp even if they don't have the vertical bar.

No vertical bar required for single-argument calls

---

src/frontend/Semantic_check.ml
src/frontend/Semantic_error.ml
src/frontend/Semantic_error.mli
test/integration/bad/data_index/rng_index1.stan
test/integration/bad/data_index/stanc.expected
test/integration/bad/stanc.expected
test/integration/bad/var-decl-bad-2.stan

Fix #526 
Toplevel declared sizes must always be (transformed) data. Code like this
```stan
generated quantities {
int N = 5;
real x[N];
}
```
has never worked but with this PR stanc3 catches the error before passing it to the C++ compiler.

Disallow rng in top level size declarations

---

src/frontend/Semantic_check.ml
src/frontend/Semantic_error.ml
src/frontend/Semantic_error.mli
test/integration/bad/array_expr_bad1.stan
test/integration/bad/array_expr_bad2.stan
test/integration/bad/stanc.expected
test/integration/good/array-expr/pretty.expected
test/integration/good/array-expr/validate_array_expr_mixed.stan

Related issue: #321 
Here's an example of what was failing:
```stan
transformed parameters {
real x[2,2] = {{1 ,2},{3 ,4}}; // ok
real y[2,2] = {{1.,2},{3.,4}}; // ok
real z[2,2] = {{1 ,2},{3.,4}}; // bad
}
```
The last array is a mix of int arrays and real arrays. Int arrays are convertible to real array but the typechecker got confused.

fix array literal type-checking

---

src/frontend/Semantic_check.ml
src/frontend/Semantic_error.ml
src/frontend/Semantic_error.mli
src/frontend/lexer.mll
test/integration/bad/numeric-literal/int-bad3.stan
test/integration/bad/numeric-literal/stanc.expected
test/integration/bad/stanc.expected
test/integration/bad/string_literal_newline.stan

Fix parser to deal with some bad literals.
* Line breaks in string literals mess up line numbering. Now disallowed. (stanc2 did allow a line break but ignored everything after it.)
* Integers larger than signed 32-bit would fail C++ compilation. Now disallowed.
* In contrast to integers, too-big reals simply overflow to infinity. Although stanc2 did not allow these they are currently allowed.

Check for invalid literals

---

src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected

Adds the following function to the model:
```cpp
std::vector<std::string> model_compile_info() const {
std::vector<std::string> stanc_info;
stanc_info.push_back("stanc_version = stanc3 66c38187 (Unix)");
stanc_info.push_back("stancflags = --warn-pedantic");
return stanc_info;
}
```
This will be used to add the compile info to the CSV and the standard output:
```
```

Add stanc info function to the model

---

src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected

In #598 we added %%NAME%% and %%VERSION%% as follows:
```ocaml
pf ppf
{|
std::vector<std::string> model_compile_info() const {
std::vector<std::string> stanc_info;
stanc_info.push_back("stanc_version = %%NAME%%3 %%VERSION%%");
stanc_info.push_back("stancflags = %s");
return stanc_info;
}
|}
```
running dune subst then building the binary and using it, it works fine. 
The problem is that --print-cpp that is used to buidl the .expected files for tests prints it as:
```
std::vector<std::string> model_compile_info() const {
std::vector<std::string> stanc_info;
stanc_info.push_back("stanc_version = %NAME%3 %VERSION%");
stanc_info.push_back("stancflags = --print-cpp");
return stanc_info;
}
```
which then means that dune subst does not work for the .expected files which broke master tests.
There …

Fix tests and dune subst bug with --print-cpp

---

src/stanc/stanc.ml
test/integration/included/dune
test/integration/included/stanc.expected
test/integration/rstanarm/data/pretty.expected
test/integration/rstanarm/dune
test/integration/rstanarm/functions/dune
test/integration/rstanarm/functions/pretty.expected
test/integration/rstanarm/gqs/dune
test/integration/rstanarm/gqs/pretty.expected
test/integration/rstanarm/model/dune
test/integration/rstanarm/model/pretty.expected
test/integration/rstanarm/parameters/dune
test/integration/rstanarm/parameters/pretty.expected
test/integration/rstanarm/pre/dune
test/integration/rstanarm/pre/pretty.expected
test/integration/rstanarm/pretty.expected
test/integration/rstanarm/tdata/dune
test/integration/rstanarm/tdata/pretty.expected
test/integration/rstanarm/tparameters/dune
test/integration/rstanarm/tparameters/pretty.expected

Fixes #468 by deprecating `--allow_undefined` and `--include_paths` in favor of `--allow-undefined` and `--include-paths`
to consistently use hyphens in all stanc arguments.

Feature/468 Use hyphens in all arguments

---

src/tfp_backend/Code_gen.ml
test/integration/tfp/tfp_models/eight_schools.py

Following [this](https://github.com/stan-dev/stanc3/issues/407#issuecomment-647777378), parameter shapes are cast to tf.int32 so they would be valid shape arguments for chain initialisation.

cast param shapes to tf.int32

---

src/middle/Stan_math_signatures.ml

- Changed for loops to List.Iters
- Changed `bare_array_type (t, 1)` to `UArray t`
- Changed the different types from functions to lists
- *_sizes is now computed for the different types

Stan math signatures code cleanup

---

src/stancjs/stancjs.ml

This is causing some false positives from rstan users.
Removing for now, should be readded with/after https://github.com/stan-dev/stanc3/issues/557

stancjs: Dont warn on uninitialized parameters by default

---

README.md
default.nix
shell.nix

- Lowered the version of Nixpkgs so that ocamlformat matches our current standard of 0.8
- Added a shell.nix that manages a bunch of the useful dev environment tools, like dune, ocamlformat and merlin
- Added support for utop
- Updated the readme to match

Improved support for Nix development

---

src/frontend/Ast_to_Mir.ml
src/stan_math_backend/Transform_Mir.ml
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/mir.expected
test/integration/good/code-gen/mother.stan
test/integration/good/compiler-optimizations/cpp.expected

Fixes issue with `transform_inits` when parameter constraints are parameters. [Discourse link](https://discourse.mc-stan.org/t/lub-free-error-possible-bug-when-initializing-parameters-bounded-by-other-parameters/17989).
For example
```stan
parameters {
real<lower=0> x;
real<lower=x> y;
}
```
Note that the lower bound for `y` is the _constrained_ `x`; in particular it is always positive. Constraining works fine and Stanc2 handled unconstraining correctly too. Unfortunately Stanc3's `transform_inits` would unconstrain `x` first and then use the _unconstrained_ value of `x` as the lower bound for `y`.
Fix parameter unconstraining bug when the constraints depend on other constrained parameters
By submitting this pull request, the copyright holder is agreeing to …

more *_free__ variables in transform_inits

---

default.nix
shell.nix

Fixing an issue with Nix installation that came up here: https://discourse.mc-stan.org/t/cmdstan-on-arm-error/18485/3
The issue occurred because of a workaround I added to simplify the shell.nix file, but it wasn't necessary so I reverted it.

Small Nix installation fix

---

src/frontend/Semantic_error.ml
test/integration/bad/stanc.expected
test/integration/example-models/knitr/curse-dims/curse-dims.Rmd

Typo fix in a semantic error message (+ corresponding test)
Probabilty -> Probability
No functional effect.

typo fix in a semantic error message

---

.github/workflows/binaries.yml

Adds a Github Action to build all binaries. If this is merged, one will be able to go under Actions -> Build binaries and start the build. The images below are from my fork where I added this to master.
A successful run "on PR" with results can be seen here: https://github.com/stan-dev/stanc3/actions/runs/377699934
This would simplify building binaries for devs that don't have access to our Jenkins. One would just fork stanc3 and get this for free.
Without cache this job takes ~40 minutes. With cache its ~5 minutes. Cache gets deleted if it has not been used for 7 days.
Added a Github Actions job to build binaries.

Build binaries with Github Actions

---

README.md
scripts/install_dev_deps.sh

Clarifies what the prerequisites are, that you need to run the install script from the scripts folders and pins merlin to version 3.4.1.
See #749 for a report and I also tried installing on a clean Ubuntu install and it failed with the 3.4.2 merlin and builds fine with 3.4.1.

Fix install instructions and script

---

src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/standalone_functions/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected

The [`reader<>`](https://github.com/stan-dev/stan/blob/develop/src/stan/io/reader.hpp#L37) class was recently update so that it could accept Eigen matrices. This PR updates the generated model code so we still preserve the virtual methods for `write_array()`, `log_prob()`, and `transform_inits()`, but underneath the hood they just call a `*_impl` method. This is nice because now that `reader` can accept an Eigen type we don't have to make temporary `std::vector<>`s and copy back and forth from  eigen vectors to std vectors.
Allows `write_array()`, `log_prob()`, and `transform_inits()` to avoid a vector copy and read/write 
license the submitted work under the BSD 3-clause license …

Allow methods that use reader to accept Eigen types

---

src/frontend/Semantic_check.ml
src/frontend/Semantic_error.ml
test/integration/bad/unnormalized/lupdf_in_lp.stan
test/integration/bad/unnormalized/lupmf_in_lp.stan
test/integration/bad/unnormalized/stanc.expected
test/integration/good/lp_transformed_param.stan
test/integration/good/pretty.expected
test/integration/good/unnormalized_math_fun_lpdf.stan
test/integration/good/unnormalized_math_fun_lpmf.stan

Prompted by issue #748 
One line change because `write_array()` method already had `lp_accum__` variable. The fact that it's not needed for anything other than `_lp` functions suggest that this may have been intented all along.
In any case, this is a backwards compatibility gotcha and [per discussion on the forum](https://discourse.mc-stan.org/t/accessing-target-in-transformed-parameters-stanc2-vs-stanc3/19432/3) something like this is needed.
Allow calling lp functions in transformed parameters block.

allow lp functions in transformed parameters

---

src/frontend/Deprecation_analysis.ml
test/integration/canonicalize/canonical.expected
test/integration/example-models/knitr/pest-control/stan_programs/pretty.expected
test/integration/example-models/misc/gaussian-process/pretty.expected
test/integration/good/function-signatures/math/matrix/pretty.expected
test/integration/good/stat_comp_benchmarks_models/pretty.expected

Minor fix: deprecation warning for cov_exp_quad suggestes using gp_cov_exp_quad. It should suggest gp_exp_quad_cov. The former one does not exist.

Fix deprecation message for cov_exp_quad

---

src/middle/UnsizedType.ml
test/integration/bad/map_rect/bad_not_enough_args.stan
test/integration/bad/map_rect/stanc.expected

Fixes #804
Fixed a bug with arguments check for `map_rect`.

Fix map_rect arg check

---

src/frontend/Semantic_check.ml
test/integration/good/lp_transformed_param.stan
test/integration/good/pretty.expected

Fix #815 
Allow user-defined _lp functions in transformed parameters block.

Fix _lp functions in transformed params

---

Jenkinsfile-test-binaries

Moved part of the jobs to 'linux-ec2' label to avoid erroring out on gelman-linux because of not being able to remove a path.

Change agents for Jenkins-test-binaries

---

Jenkinsfile

Added build stage for ARM in Jenkinsfile.  
I have added a new EC2 Fleet for ARM with 0 instances so it will spin up only when we need it, this way we can now easily build ARM for other projects too.  

Building ARM binaries in the pipeline

---

src/stan_math_backend/Locations.ml
src/stan_math_backend/Stan_math_code_gen.ml
test/integration/cli-args/filename_good.expected
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/opencl/cpp.expected
test/integration/good/code-gen/profiling/cpp.expected
test/integration/good/code-gen/standalone_functions/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected
test/unit/Stan_math_code_gen_tests.ml

This does three things
1. Makes `locations_array__` into a `static constexpr std::array<const char*, {size_of_error_list}>`
2. Moves `current_statement__` to be created inside of local function scopes.
3. Adds spaces to the templates for the `_impl` functions so they are a little easier to read.
(1) is just a nice optimization. That array is only read from and we can deduce the size in the compiler so we just make it a `static constexpr` array of `const char*` so the compiler knows it's size and `static` so that it knows that global can only be accessed inside this file.
(2) is related to [#897](https://github.com/stan-dev/cmdstan/pull/987) which let's a Stan program run with multiple chains in one program. Having `current_statement__` as a global variable means that when we call log prob …

Make locations_array constexpr and move curr_statement__ to function scope

---

src/stan_math_backend/Stan_math_code_gen.ml
test/integration/cli-args/filename_good.expected
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/opencl/cpp.expected
test/integration/good/code-gen/profiling/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected

I was getting compiler errors with the line:
```cpp
static constexpr char* function__ = "gauss3D_model_namespace::gauss3D_model";
```
The warning is:
```
warning: ISO C++11 does not allow conversion from string literal to 'char *const' [-Wwritable-strings]
```
If I add another `const` then they go away:
```cpp
static constexpr const char* function__ = "gauss3D_model_namespace::gauss3D_model";
```
I guess constexpr does not imply const.
Fixes #844 hopefully

Add const to constexpr char* variables (Issue #844)

---

Jenkinsfile

The compile tests in #856 seem to be taking way longer than before. Last master run they took a little under 24 minutes, on PR they take 2-3hours.

Set -j PARALLEL in compile tests

---

src/analysis_and_optimization/Monotone_framework.ml
src/analysis_and_optimization/Optimize.ml
src/analysis_and_optimization/Partial_evaluator.ml
test/unit/Optimize.ml

Fix #890 . C++ considers divide-by-zero undefined behavior but I think throwing an exception is the best option.
Fix optimizer crash on divide-by-zero expressions.

handle divide-by-zero in partial evaluator

---

Jenkinsfile
RELEASE-NOTES.txt

This PR just merges the release branch (contains release notes) and attempts to fix the issues we were having in testing where end-to-end tests occasionally threw
```
fatal error: file '/usr/include/errno.h' has been modified since the precompiled header 'stan/src/stan/model/model_header.hpp.gch' was built
note: please rebuild precompiled header 'stan/src/stan/model/model_header.hpp.gch'
```
which means that somewhere a `make clean-all` was not happening properly.

Fix testing error

---

src/middle/Warnings.ml

We don't emit a newline after printing warnings:
```
stanc3$ ./run pedantic-mode-example.stan --warn-pedantic
Warning: The parameter c has no priors.
Warning: The parameter b has no priors.
Warning: The parameter a has no priors.stanc3$
```
I'm guessing that's causing this issue: https://discourse.mc-stan.org/t/bugs-in-pedantic-mode/22961/3
But even if it's not, that's some weird formatting. The new behavior is:
```
stanc3$ ./run pedantic-mode-example.stan --warn-pedantic
Warning: The parameter c has no priors.
Warning: The parameter b has no priors.
Warning: The parameter a has no priors.
stanc3$
```

Add newline after warnings are printed

---

src/frontend/parser.mly
src/middle/Warnings.ml
src/middle/Warnings.mli
test/integration/bad/stanc.expected
test/integration/rstanarm/pre/pretty.expected

This is addressing #905. 
The new output is:
```
$ touch empty.stan
$ ./_build/default/src/stanc/stanc.exe empty.stan 
Warning: Empty file 'empty.stan' detected; this is a valid stan model but likely unintended!
```
The change is done in the parser rather than the lexxer so that a file of only comments still produces the warning. This may (or may not) want to be changed based on #93, but it is a simple enough fix for now. One test was added, integration/bad/empty.stan, and a few existing test outputs were updated to include this warning.
A warning is now produced if an empty file is compiled.

Produce a warning for empty files

---

src/stancjs/stancjs.ml
test/stancjs/data-generation.js
test/stancjs/info.js
test/stancjs/stancjs.expected

Stancjs was missing some of Stanc3's command line options. I've added `--info` and `--debug-generate-data` which seem like the most useful ones. The other missing options are all for parser debugging or printing various stages of the MIR.
Stancjs now has `--info` and `--debug-generate-data` options.

Add --info and --debug-generate-data flags to stancjs

---

src/frontend/Input_warnings.ml
src/frontend/Input_warnings.mli
src/frontend/Parse.ml
src/frontend/lexer.mll
src/frontend/parser.mly
src/middle/Warnings.ml
src/middle/Warnings.mli

This completes some internal reorganization mentioned in #869. It moves the warnings "Hack" used by the parser/lexer out of the Warnings module and into its own module in the frontend. This should prevent confusion caused by trying to use the stateful part of the warnings in parts of the code after the parser.
Reorganized warning system internally.

Move input warnings to separate module

---

README.md

When following the current directions to build `stanc3` with `make`, I get the error:
```+ install_missing='t know how to build scripts/src/stanc/stanc.exe'
+ echo 'Trying to install missing deps for stanc with t know how to build scripts/src/stanc/stanc.exe'
Trying to install missing deps for stanc with t know how to build scripts/src/stanc/stanc.exe
+ t know how to build scripts/src/stanc/stanc.exe
setup_dev_env.sh: line 15: t: command not found
```
This looks like `bash` attempting to parse the output of `dune external-lib-deps --missing src/stanc/stanc.exe`, which gives:
```Entering directory '/Users/chrislambda/stanc3'
Error: Don't know how to build scripts/src/stanc/stanc.exe
```
The error seems to be due to the fact that `scripts/src/stanc` doesn't exist; if the setup script is run …

Fix build directions with `make`

---

src/middle/Stan_math_signatures.ml
test/integration/good/function-signatures/math/matrix/pretty.expected
test/integration/good/function-signatures/math/matrix/to_matrix.stan
test/integration/signatures/stan_math_sigs.expected

Fixes #928 
Added `to_matrix(array[] row_vector) => matrix`

Add `to_matrix(array[] row_vector)`

---

.github/pull_request_template.md

This change is motivated in part by the discussion in https://github.com/stan-dev/docs/issues/372 and again by https://github.com/stan-dev/docs/issues/379. We should have a submission checklist that requests either a link to the documentation PR, or a acknowledgement that the PR needs no further documentation.
The template I propose looks like this:
----
[Internal] Updated contribution template in attempt to keep docs in sync

Add PR checklist to template

---

Jenkinsfile

I think there is no real need to build all the various Linux binaries for different archs on PRs given that they are not published on PRs. I left the arm architecture, so that we try to build with one of them, just to make sure there are no suprises. I missed this when reviewing the original PR.
@andrjohns are you cool with this?

Build non-x86 and arm binaries on pushes to master only

---

src/frontend/Info.ml
src/frontend/Preprocessor.ml
src/frontend/Preprocessor.mli
test/integration/cli-args/dune
test/integration/cli-args/included.stan
test/integration/cli-args/includes/another_include.stan
test/integration/cli-args/includes/recursive.stan
test/integration/cli-args/info.expected
test/integration/cli-args/info.stan
test/stancjs/stancjs.expected

This should close #808. The files included by the preprocessor are now part of the JSON output
Added a list of included files to the information provided by --info

Add included files to --info

---

src/frontend/Pretty_printing.ml
test/integration/canonicalize/canonical.expected
test/integration/canonicalize/squaremc.stan
test/integration/rstanarm/pretty.expected

I'm working on a machine-update of the example models repo, which is really testing out the pretty-printing now that we have comments preserved. Here is the latest example of weirdness (see also #967):
The [squaremc.stan](https://github.com/stan-dev/example-models/blob/master/bugs_examples/vol3/funshapes/squaremc.stan) model currently has something that gets pretty-printed to
```stan
real<lower=-(1 - sqrt(1 - square(1 - fabs(x_raw)))), upper=(1
- sqrt(
1
- square(
1 - fabs(x_raw))))> y_raw;
```
I've fixed this and added this file to the tests (it's also a great example of what the canonicalizer can do, so it's under those tests)
Better pretty-printing for long constraints
license the submitted work under …

Better pretty-printing for long constraints

---

Jenkinsfile
docker/multiarch/README.md
docker/static/Dockerfile
scripts/build_multiarch_stanc3.sh

The current multiarch builds are failing because one of the files are no longer available to download. This PR fixes that by replacing the use of a dockerfile which is built and run, with a pre-built docker image that has the necessary files included
Fix automated builds of non-x86 architectures

Fix multiarch stanc3 builds

---

src/middle/Errors.ml
test/integration/cli-args/notfound.expected

Currently we print out "Cannot not open...". This fixes the double negative and changes the message to be a bit more informative and in line with our other errors/warnings.
Fixed a typo in the error message displayed when a file cannot be found

Fix typo in file not found error

---

src/frontend/Frontend_utils.ml
src/frontend/Preprocessor.ml
src/middle/Errors.ml
src/middle/Semantic_error.ml
src/middle/Warnings.ml
test/integration/bad/stanc.expected
test/stancjs/stancjs.expected

Currently, parsing errors always have newlines at the end, added by Menhir. Our semantic error messages and lexing error messages didn't, so they would result in a command line prompt like
```
Invalid character found.[brian@Flatiron stanc3 on master [!?]] $ 
```
This change simply adds "@." (the format newline/flush command) to the end of the non-parsing errors. Note that this doesn't effect the captured test output, so the diff doesn't have to edit every single fail test in the project.
Error messages should now always have a trailing newline.

Always flush after semantic and lexical errors

---

src/frontend/Frontend_utils.ml
src/middle/Warnings.ml
test/integration/bad/lang/stanc.expected
test/integration/bad/new/stanc.expected
test/integration/bad/stanc.expected

This is somewhat of a follow on to #982. If we don't get it in 2.28 that's probably okay.  
We were outputting input warnings with a piece of code that duplicated `Warnings.pp_warnings` but not as well. The result was that the newlines were not properly handled. This was especially noticeable if you had a warning and error in the same file, as the error would just get appended to the line rather than following it. 
See changed test output for examples
Display errors on separate lines from warnings if both exist

Display lexer warnings the same as others

---

src/frontend/Typechecker.ml
test/integration/good/matrix_pow_warning.stan
test/integration/good/pretty.expected

Replacement for #994, closes #604 
Emit warning for `matrix^scalar` and point users to `.^` and `matrix_power()`.

Warn for matrix^pow, suggest .^ or matrix_power()

---

src/frontend/parser.messages
test/integration/bad/new/fundef-bad10.stan
test/integration/bad/new/stanc.expected
test/integration/bad/stanc.expected

This came up on the forums [here](https://discourse.mc-stan.org/t/within-chain-parallelization-not-working-with-cmdstanr-on-linux-server/25203/7?u=wardbrian)
We currently generate a warning that just says the type must be unsized, which is confusing when you declare something like `corr_matrix` without sizes. I've added a test that does just this as well.
Improve error messages when a user tries to declare a function argument as a constrained type

Note that function arguments must be both unsized *and* unconstrained

---

src/analysis_and_optimization/Mir_utils.ml
src/analysis_and_optimization/Optimize.ml
src/analysis_and_optimization/Partial_evaluator.ml
src/common/Common.ml
src/common/Common.mli
src/common/FatalError.ml
src/frontend/Ast.ml
src/frontend/Ast_to_Mir.ml
src/frontend/Debug_data_generation.ml
src/frontend/Errors.ml
src/frontend/Errors.mli
src/frontend/Pretty_printing.ml
src/frontend/Semantic_error.ml
src/frontend/Typechecker.ml
src/frontend/dune
src/frontend/parser.mly
src/middle/Expr.ml
src/middle/Stan_math_signatures.ml
src/middle/Stmt.ml
src/stan_math_backend/Expression_gen.ml
src/stan_math_backend/Stan_math_code_gen.ml
src/stan_math_backend/Statement_gen.ml
src/stan_math_backend/Transform_Mir.ml

This closes #76 
It adds `Common.FatalError.fatal_error_msg`, which is a drop-in replacement for `raise_s` that prepends the following message:
`Fatal error: this should never happen. Please file a bug on https://github.com/stan-dev/stanc3/issues/new.`
and `Common.FatalError.fatal_error` which is the same as the above but doesn't take in any additional message/sexp.
We previously had a Frontend.Errors.fatal_error, but it wasn't used, and it felt like it should live in Common (rather than importing the frontend into the code generator, for example).
I also updated all existing calls to either `raise_s` or `failwith` in the compiler.
All internal compiler errors now include a link to the stanc3 issues page.
By submitting this pull request, the copyright holder is agreeing to …

Standardize internal compiler error messages

---

Jenkinsfile

Fixed odoc job in the pipeline, we had a permission issue because in the upstream opam 4.12 image they changed a little the groups to as it was with 4.07

Fixed odoc job permission issue

---

Jenkinsfile
Jenkinsfile-test-binaries
scripts/build_multiarch_stanc3.sh

Following #1019, we have Jenkins using images like `stanorg/stanc3:static-ocaml-update`. @serban-nicusor-toptal is going to rename those back to the standard names (without `-ocaml-update`) now that it is merged, and this will go along with that.

Point Jenkins back to main docker images

---

scripts/build_multiarch_stanc3.sh

There is an edge case where when we're building multiarch in listing of docker volumes to attach we're listing all containers (including inactive) so that can result in a broken docker run command generated, this PR is supposed to fix that by listing only running containers, since we're having 1 executor/runner that will always be one.
Example:
```
~home/serban-nicusor-toptal$ docker ps -aqf "ancestor=stanorg/stanc3:static"
14b082be5021
1cb3db4a06ff
6562418e57b8
8bc2eb99e616
9fb896708856
d4cdf602d5e7
944eeb1dca29
```

List volumes only for running containers when building multiarch

---

src/frontend/Deprecation_analysis.ml
src/frontend/Typechecker.ml
src/middle/UnsizedType.ml
src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/fun-defs-lpdf.stan
test/integration/good/pretty.expected

Closes #1045. The is_int_type and is_real_types now check the type recursively to handle nesting, and `lpdf` is defined not by 'takes a real as the first argument' but (properly) as 'does _not_ take an int as the first argument'
This is consistent with the final paragraph given [here](https://mc-stan.org/docs/2_28/stan-users-guide/user-defined-probability-functions.html) already
Allow user-defined densities over complex arguments and deeply nested arguments.

User-defined densities allowed over nested and complex values.

---

src/frontend/Ast.ml
src/frontend/Input_warnings.ml
src/frontend/Input_warnings.mli
src/frontend/parser.mly
test/integration/bad/lang/stanc.expected
test/integration/bad/new/stanc.expected
test/integration/good/pretty.expected

Related to #953 and essentially the start of redoing https://github.com/stan-dev/stan/issues/2712
Warn about the following identifiers being reserved in a future version: 
`array`, `upper`, `lower`, `offset`, `multiplier`.

Warn about future reserved words

---

.github/workflows/binaries.yml

What the title says and not much more. Also removed building stan2tfp binaries. 
Sidenote: I was unable to use the stanorg/stanc3:debian docker image, as I got an error:
```
Read 505 sample input sentences and 359 error messages.
ocamlopt src/stanc/stanc.exe (exit 2)
(cd _build/default && /github/home/.opam/4.12.0/bin/ocamlopt.opt -ccopt -static -g -o src/stanc/stanc.exe /github/home/.opam/4.12.0/lib/base/base_internalhash_types/base_internalhash_types.cmxa -I /github/home/.opam/4.12.0/lib/base/base_internalhash_types /github/home/.opam/4.12.0/lib/base/caml/caml.cmxa /github/home/.opam/4.12.0/lib/sexplib0/sexplib0.cmxa /github/home/.opam/4.12.0/lib/base/shadow_stdlib/shadow_stdlib.cmxa /github/home/.opam/4.12.0/lib/base/base.cmxa -I /github/home/.opam/4.12.0/lib/base …
```

Upgrade GHA for building binaries to work with OCaml 4.12

---

src/analysis_and_optimization/Pedantic_analysis.ml
test/unit/Pedantic_analysis.ml

In pedantic mode, we sometimes use the word `twiddle` instead of `tilde`. I know they are considered synonyms, but given that we used tilde everywhere else (parser, docs, etc), it should be tilde here as well.
Replaced the use of the word twiddle with tilde in pedantic warning messages.

Replace use of `twiddle` with `tilde`

---

src/frontend/Ast.ml
src/frontend/Pretty_printing.ml
src/frontend/lexer.mll
test/integration/canonicalize/canonical.expected
test/integration/rstanarm/pretty.expected

See #990.
I didn't change the AST to record more info; this just extends the "array-expr" hack to binary operators. Probably has some corner cases where comments are misplaced anyway but for now I think it's an improvement over what we had before.
The logic is also not as simple as it probably could be but again, not worse than before, just more of the same.

Improve pretty printing comments inside binary ops

---

src/analysis_and_optimization/Optimize.ml
src/analysis_and_optimization/Partial_evaluator.ml
src/common/FatalError.ml
src/frontend/Ast.ml
src/frontend/Ast_to_Mir.ml
src/frontend/Debug_data_generation.ml
src/frontend/Pretty_printing.ml
src/middle/Expr.ml
src/stan_math_backend/Expression_gen.ml

Removes `FatalError.fatal_error` in favor of `FatalError.fatal_error_msg`, refactors to remove a few fatal error branches, and elaborates some other fatal error messages.
Also fixes an issue with `--debug-generate-data` if the data block has extra semicolons.
```stan
data {
real x;; // compiles to C++ but --debug-generate-data crashes
}
```

Cleanup fatal_error usage

---

src/frontend/Typechecker.ml
test/integration/bad/lang/reused_name.stan
test/integration/bad/lang/stanc.expected

Silly mistake on my part when merging the symbol table in #995.  Realized it would be a 1 line fix so I decided not to wait @rok-cesnovar. 
Closes #1060 
Fixes a bug not in the last release (#1060)

Properly verify a variable name isn't in use

---

src/frontend/Typechecker.ml
test/integration/good/lang/good_early_reject.stan
test/integration/good/lang/pretty.expected
test/integration/good/lang/unreachable_statement.stan

This fixes #1062. The issue made me realize it would probably be good if the typechecker warned you when there were unreachable statements, as they are almost always unintentional (the model which provoked #1062 did so because it had an unconditional `reject` which was probably a bug).
Issue a warning when a user has a model with unreachable statements, such as code following a `return` statement.

Fix typechecker issue with unreachable statements, emit warning

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/todo.md

This adds a few issue templates to the repo to help with bug reports. When users click 'New Issue', this adds a selection screen before opening a template for them. To see what they look like, you can navigate here:
https://github.com/WardBrian/stanc3/issues/new/choose 
Added issue templates to the stanc3 repo

Add issue templates

---

src/frontend/Preprocessor.ml
test/stancjs/good_after_bad.js
test/stancjs/stancjs.expected

This fixes an issue first spotted by @spinkney in #577. The preprocessing stack is never cleared, so in particular a subsequent parse will inherit anything left on the stack. This is only possible to trigger in the Javascript compiler.
Removing the change in `Preprocessor.ml` makes the new test fail like so:
```
Syntax error in 'string', line 8, column 0 to column 5, parsing error:
Expected "generated quantities {" or end of file after end of model block.
Syntax error in 'string', line 8, column 6 to column 7, parsing error:
Expected "generated quantities {" or end of file after end of model block.
```
Fix an issue with parser errors 'sticking around' on subsequent runs, which primarily affected the Javascript compiler
By submitting this pull request, the copyright holder …

Clear lexing stack before parsing starts

---

src/frontend/Deprecation_analysis.ml
src/frontend/Input_warnings.ml
src/frontend/lexer.mll
test/integration/bad/new/stanc.expected
test/integration/cli-args/canonicalize/everything-but.expected
test/integration/good/warning/pretty.expected
test/integration/included/stanc.expected
test/stancjs/stancjs.expected

I realized during today's Stan meeting that the warning messages are specific to stanc3 on the command line, and wouldn't even make sense for the javascript interface.
This pr transitions from messages like 
> This can be changed automatically using stanc --auto-format
to
> This can be changed automatically using the auto-format flag to stanc
This is more useful for non-command line interfaces. It's a little less immediately actionable, but it still tells you there is a way to do it for your interface. 
I'm happy to iterate on it more if there are suggestions
Updated warning messages

Make warning messages not specific to command line

---

Jenkinsfile

Fixes the issue that caused stanc3 master to fail. If not otherwise specified, we checkout the master branches of CmdStan/Stan/Math, but we want to work with develop branches.

Checkout develop for CmdStan/Stan/Math by default, not master

---

src/frontend/Pretty_printing.ml
src/stanc/stanc.ml
src/stancjs/stancjs.ml
test/stancjs/debug.js
test/stancjs/math_sigs.js
test/stancjs/optimization.js
test/stancjs/stancjs.expected

This is not completely done yet as I am having two issues:
- I am not sure if/how we can return the "pretty" prints (`debug-mir-pretty`, `debug-transformed-mir-pretty`, etc.) I am not sure how to replace this call to make it return a string: `Program.Typed.pp Format.std_formatter tx_mir`
- The stan math signatures hashtbl seems to be empty when called with stancjs. See comment.
Add optimization level flags, debug-* and dump-math-signatures flags to stancjs.

Add optimization flags, debug-* flags to stancjs

---

src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/ode/cpp.expected
test/integration/good/code-gen/overloading_templating.stan
test/integration/good/code-gen/standalone_functions/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected
test/integration/good/compiler-optimizations/mem_patterns/cpp.expected
test/unit/Stan_math_code_gen_tests.ml

Closes #1105 by adding `require_*` templates to the code generated by user-defined functions.

Add require_* templates to generated functions

---

Jenkinsfile

After the discussion in https://github.com/stan-dev/math/issues/2623, we've decided to build osx binaries differently for release and develop.
- develop and pull requests will be built on flatiron osx 11.2
- master (nightly) and tags (releases) will be built on gelman osx 10.11.6

Separated osx build for develop and releases

---

src/frontend/Pretty_printing.ml
test/integration/cli-args/canonicalize/canonical.expected
test/integration/cli-args/canonicalize/deprecations-only.expected
test/integration/good/fun_log_forward_decl.stan
test/integration/good/pretty.expected

Closes #1119 
Do not print `|` if a distribution is called with only one argument.

Remove | if only one argument is supplied

---

Jenkinsfile
README.md

Improve CI builds times by splitting compile tests and running them in parallel.

Split compile tests into smaller chunks to improve CI times

---

src/analysis_and_optimization/Debug_data_generation.ml
src/analysis_and_optimization/Debug_data_generation.mli
src/analysis_and_optimization/Dependence_analysis.ml
src/analysis_and_optimization/Dependence_analysis.mli
src/analysis_and_optimization/Mem_pattern.ml
src/analysis_and_optimization/Mir_utils.ml
src/analysis_and_optimization/Mir_utils.mli
src/analysis_and_optimization/Optimize.ml
src/analysis_and_optimization/Pedantic_analysis.ml
src/frontend/Ast_to_Mir.ml
src/frontend/Ast_to_Mir.mli
src/middle/Expr.ml
src/middle/Expr.mli
src/stanc/stanc.ml
src/stancjs/stancjs.ml
test/unit/Debug_data_generation_tests.ml

After #1115 `Debug_data_generation.ml` lives in `analysis_and_optimization` instead of `frontend` and it should no longer use `Frontend.Ast`. This PR removes Ast from data generation.
Also, generation of matrices with non-scalar lower/upper bounds was broken; I fixed that too.

Debug_data_generation fixes

---

src/frontend/Semantic_error.ml
src/frontend/Semantic_error.mli
src/frontend/Typechecker.ml
test/integration/bad/assigment-to-function-stanmath.stan
test/integration/bad/assignment-to-function.stan
test/integration/bad/stanc.expected

Closes #1101
Fixed a bug in the typechecker which permitted assignments to function values and produced un-compilable C++

Prevent assignments of function types

---

src/frontend/Semantic_error.ml
src/frontend/SignatureMismatch.ml
src/frontend/SignatureMismatch.mli
src/middle/Stan_math_signatures.ml
test/integration/bad/compound-assign/stanc.expected

Currently our type errors produced from assignment operators like `*=` are very different than something like `operator*`. In particular, we don't truncate the list at all. This PR introduces two changes:
1. Truncate the shown signatures at 5 (same as any other signature error)
2. Only show signatures which match the LHS provided. For example,
```stan
row_vector[N] x;
x *= x;
```
Does not need to show the `int*int` signature, but should show `row_vector*real`, etc.
Improve error messages when an assignment operator like `+=` is given bad types.

Only show assignment operators which match the lhs in error messages

---

src/frontend/Semantic_error.ml
src/frontend/SignatureMismatch.ml
src/frontend/SignatureMismatch.mli
src/frontend/Typechecker.ml
test/integration/bad/function-signatures/overloading/stanc.expected
test/integration/bad/signature_sampling_udf.stan
test/integration/bad/stanc.expected

Currently, no matter what goes wrong when typechecking a statement like `x ~ foo(3)`, the same error is output if `foo` is invalid:
`Ill-typed arguments to '~' statement. No distribution 'foo' was found with the correct signature.`
This is much weaker than for other function errors, which will output valid signatures or ambiguous match results. This PR simply tries to make them look more like function signature errors. It's not perfect (a 100% ideal error might try to re-construct the `~` notation rather than formatting them like the function calls they are under the hood) but it's certainly much more informative than before.
Improve type errors generated in `~` statements.
license the submitted work …

Improve tilde statement type errors

---

src/stan_math_backend/Stan_math_code_gen.ml
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/overloading_templating.stan
test/unit/Stan_math_code_gen_tests.ml

Fixes a bug reported here: https://discourse.mc-stan.org/t/cmdstan-2-29-1-compile-error/26793/10
This updates the test `test/integration/good/code-gen/overloading_templating.stan` such that it fails on `master`

Fix compilation error with forward declarations

---

src/middle/Expr.ml
test/unit/Optimize.ml

Spotted while debugging #1151, the MIR pretty-printer will print expressions which look incorrect due to the lack of parenthesis. For example, the code ` (1 ? x : y) * 3` would be printed as ` 1 ?x :y * 3` which would have a different associativity. 
MIR pretty printing now always adds ( and ) around the ternary operator `?:`

Always print () around ternary operator in MIR

---

src/frontend/Typechecker.ml
test/integration/bad/complex_mat_bad.stan
test/integration/bad/stanc.expected

Fix indexing of a complex container to return the correct type

Fix return type of indexing operations on complex containers

---

src/frontend/Info.ml
src/frontend/dune
test/integration/cli-args/info/info.expected
test/stancjs/stancjs.expected

This is similar to what we do in code generation, and will make writing the types of tuples much easier (e.g #820). The contents of the output are identical.
The `--info` command now uses the Yojson library for it's output.

Use Yojson for --info output

---

src/middle/Stmt.ml
test/integration/good/code-gen/complex_numbers/complex_data.stan
test/integration/good/code-gen/complex_numbers/cpp.expected

A small bug where the order of the for loops to read in a matrix were swapped. This didn't change any test output, because the matrices in the test file were square, so I added a test which shows it (now).
Fix an issue reading in `complex_matrix` in the data block

Fix complex matrix reads

---

src/middle/Stan_math_signatures.ml
test/integration/signatures/stan_math_signatures.t

For downstream processing, it's very difficult to handle long signatures that get split over multiple lines. And, in my opinion, it doesn't make them more human-readable either. This prints the entire signature on one line regardless of length. 
`--dump-stan-math-signatures` now prints an entire signature on one line, no matter how long it is. 

Dump math signatures with one line per signature

---

src/stan_math_backend/Function_gen.ml
test/integration/good/code-gen/complex_numbers/cpp.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/ode/cpp.expected
test/integration/good/code-gen/standalone_functions/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected
test/integration/good/compiler-optimizations/mem_patterns/cpp.expected

This requires https://github.com/stan-dev/math/pull/2694
Improve compile times by accumulating all template requirements into a single `require_all_t` on user defined functions.

Collapse all require templates into a require_all

---

src/common/Helpers.ml
src/middle/Stan_math_signatures.ml
test/integration/good/function-signatures/math/matrix/cumulative_sum.stan
test/integration/signatures/stan_math_signatures.t

Expose an overload for `cumulative_sum` which takes and returns an array of integers.
Expose overloads for `cumulative_sum` which work for complex arrays and vectors. 

Expose cumulative sum for integers and complex types

---

src/frontend/Errors.ml
src/frontend/Errors.mli
src/middle/Location.ml
src/stancjs/stancjs.ml
test/stancjs/stancjs.expected

This refactors some of the error printing code to isolated the file-reading from the logic which creates an error.
As a bonus this allows us to pass in the code string from the JS compiler to also format an error.
So, something which currently looks like
```
Semantic error in 'string', line 3, column 8 to column 11: 
Function is declared without specifying a definition.
```
Would now look like 
```
Semantic error in 'string', line 3, column 8 to column 11:
-------------------------------------------------
1:  
2:  functions {
3:      int foo(real a);
^
4:  }
5:  transformed data {
-------------------------------------------------
Function is declared without specifying a definition.
```
This example is taken from the test output of the stancjs integration tests.
The …

Show source code context with errors in Javascript

---

src/common/Fixed.ml
src/common/Helpers.ml
src/middle/Expr.ml
src/middle/Index.ml
src/middle/Program.ml
src/middle/SizedType.ml
src/middle/Stmt.ml
src/middle/UnsizedType.ml

The MIR pretty printing had a few oddities in it. It used quoted strings `{| ... |}` instead of normal string literals `" ... "` without needing to, and it would associate a color/style with keywords. We don't (and can't) really print things out in color, so that doesn't need to happen. 
Cleaned up code for pretty printing the Middle Intermediate Representation (MIR)

Clean up MIR pretty printing code

---

src/analysis_and_optimization/Mem_pattern.ml
src/common/Helpers.ml
src/middle/SizedType.ml
src/stanc/stanc.ml
src/stancjs/stancjs.ml
test/integration/cli-args/canonicalize/canonicalize.t
test/integration/cli-args/stanc.t
test/integration/good/compiler-optimizations/mem_patterns/dune
test/integration/good/compiler-optimizations/mem_patterns/transformed_mir.expected

Closes #1135 
Added `--debug-mem-patterns` flag, which will print out the memory type of variables (either Array of Structs or the more efficient Struct of Arrays pattern) when optimization is enabled. 

Add --debug-mem-patterns flag

---

src/middle/Stan_math_signatures.ml
test/integration/good/function-signatures/math/matrix/log_determinant_spd.stan
test/integration/signatures/stan_math_signatures.t

Added `log_determinant_spd` which is faster when the input matrix is known to be symmetric and positive definite.

expose log determinant spd

---

scripts/install_build_deps.sh

Apparently installing a specific version is not enough to prevent a newer version from being installed, so we should just pin core to v0.14

Pin core kernel to v0.14

---

src/frontend/Deprecation_analysis.ml
src/middle/Stan_math_signatures.ml
src/middle/Stan_math_signatures.mli
test/integration/signatures/stan_math_distributions.t

We currently assume whenever a function has a Lp[md]f signature, it must also have a _log, unless it is a GLM. This creates issues for things like #1188, which want to add new distributions but don't support the deprecated/soon to be removed _log suffix. This change makes it so that Log is explicitly listed as a function type for signatures, so in particular it does not always need to be present. 
Allowed the adding of new distributions without requiring them to support deprecated suffixes. 

Make log suffix explicit in declarative distribution signatures

---

src/stan_math_backend/Stan_math_code_gen.ml
test/integration/cli-args/filename_good.expected
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/complex_numbers/cpp.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/ode/cpp.expected
test/integration/good/code-gen/opencl/cpp.expected
test/integration/good/code-gen/profiling/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected
test/integration/good/compiler-optimizations/mem_patterns/cpp.expected

Fixes the issue spotted in #1165 

Fix size of output vector in write_array

---

src/frontend/Ast.ml
src/frontend/Ast_to_Mir.ml
src/frontend/Canonicalize.ml
src/frontend/Info.ml
src/frontend/Pretty_printing.ml
src/frontend/Typechecker.ml
src/frontend/parser.mly
test/unit/Parse_tests.ml

We currently have the type of VarDecl set up so that it could hold an unsized type. This is never done in the AST, and leads to a lot of unecessary hand-wringing, like this unreachable code in the typechecker:
```ocaml
| VarDecl {decl_type= Unsized _; _} ->
(* currently unallowed by parser *)
Common.FatalError.fatal_error_msg
[%message "Don't support unsized declarations yet."]
```
We cannot do the same in the MIR, since certain optimizations actually can produce unsized declarations, namely function inlining 
#1097 
Internally clean up how variable declarations are represented.

Clean up AST by specifying vardecl as sized

---

default.nix
shell.nix

This was never done following #1019. I briefly tested inside the nix-os docker containers to confirm that it now builds stanc again.

Update nix files to use ocaml 4.12

---

src/frontend/Canonicalize.ml
src/frontend/Deprecation_analysis.ml
src/frontend/Typechecker.ml
src/middle/Operator.ml
test/integration/cli-args/canonicalize/canonical.expected
test/integration/cli-args/canonicalize/deprecated.stan
test/integration/cli-args/canonicalize/deprecations-only.expected
test/integration/cli-args/canonicalize/everything-but.expected
test/integration/cli-args/canonicalize/parenthesize.stan
test/integration/good/pretty.expected
test/integration/good/validate_logical_negate_expr_good.stan
test/integration/good/warning/deprecated_syntax.stan
test/integration/good/warning/pretty.expected
test/integration/good/warning/unreachable_statement.stan
test/stancjs/stancjs.expected

Closes #494 and touches on #823 . Those issues have not received any feedback, not sure if it's because everyone agrees or because no one reads the issue tracker.
* Deprecate using real scalar as a boolean
* Warn about ambiguous comparison operator chains

some deprecations

---

src/stan_math_backend/Statement_gen.ml
test/integration/good/code-gen/complex_numbers/cpp.expected
test/integration/good/compiler-optimizations/mem_patterns/cpp.expected

This tweaks code gen slightly to initialize empty complex Eigen types to have `nan` for both the real and imaginary portions. 
Currently, the model:
```stan
transformed data {
complex_vector[1] Z;
}
model {
print(Z[1]);
}
```
prints `(nan, 0)`. This PR makes that `(nan, nan)`

Initialize complex types to NaN for both components

---

src/analysis_and_optimization/Pedantic_analysis.ml
test/integration/cli-args/warn-pedantic/missing-prior-false-alarm.stan
test/integration/cli-args/warn-pedantic/stanc.expected

This is a partial fix for #932. The problem is well summarized by @rybern [on the forums](https://discourse.mc-stan.org/t/misleading-warning-when-providing-prior-parameters-as-data/27289/4?u=rybern). I'm not sure entirely how to go about resolving the issue, but we should be more transparent in the warning until it is fixed.
Improved the pedantic mode warning for parameters without priors. The message now highlights when it is safe to ignore.

Make warning for no priors more descriptive

---

src/stan_math_backend/Stan_math_code_gen.ml
src/stan_math_backend/Stan_math_code_gen.mli
src/stanc/stanc.ml
src/stancjs/stancjs.ml
test/stancjs/optimization.js
test/stancjs/stancjs.expected

The generated `model_compile_info` will now feature arguments  passed in from stancjs

Allow driver code to set printed argument list in generated hpp

---

src/stan_math_backend/Stan_math_code_gen.ml
test/integration/cli-args/filename_good.expected
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/complex_numbers/cpp.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/ode/cpp.expected
test/integration/good/code-gen/opencl/cpp.expected
test/integration/good/code-gen/profiling/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected
test/integration/good/compiler-optimizations/mem_patterns/cpp.expected

Reverts stan-dev/stanc3#1241
This PR broke Stan tests. Until we have a plan to do all the changes required we should revert

Revert "Add get_param_names overload with flag arguments"

---

src/middle/Stan_math_signatures.ml
test/integration/good/function-signatures/math/matrix/complex_schur_decompose.stan
test/integration/signatures/stan_math_signatures.t

Added functions `complex_schur_decompose_t` and `complex_schur_decompose_u` implementing the complex-valued Schur decomposition for matrices. 

Expose complex Schur decomposition functions

---

Jenkinsfile

Don't run ocaml tests in isolated directories, cleanup at the end of the pipeline
There seems to be an issue with dune running from a child directory inside stanc3.
Before, we aimed for running each step with it's own source code isolated but since we were puttin stanc3 inside stanc3, example {path}/{stanc3 source code}/dune-tests/{stanc3 source code for this step} dune is running into an error
```
Entering directory '/tmp/stanc3'
Error: Too many opam files for package "stanc":
- dune-tests/stanc3/stanc.opam
- stanc.opam
```
This PR will execute the tests from the root of the working directory, therefore not running into this edge case.
license the submitted work under the BSD 3-clause license …

Fix dune tests in ci

---

Jenkinsfile
scripts/build_multiarch_stanc3.sh

Use --root when running in isolated directories to avoid dune automatically guessing the root directory in CI.

Do not let dune automatically guess root dir in CI

---

.github/workflows/binaries.yml
Jenkinsfile

This PR sets up our Github Actions run to use an older version of the MacOS SDK, allowing the built binaries to be used on older versions than the system which built them. 
Hopefully we will soon be able to do the same thing as part of the Flatiron Jenkins build, but even without it this removes the need for the gelman mac instances, since we could use this during releases if necessary. 
See sample run [here](https://github.com/WardBrian/stanc3/actions/runs/3154503248)

Github Actions: Build backwards-compatible Mac executables

---

Jenkinsfile

CI change, build backwards-compatible Mac executables on flatiron mac.

Build backwards-compatible Mac executables on flatiron mac

---

src/frontend/Environment.ml
src/frontend/Environment.mli
src/frontend/Semantic_error.ml
src/frontend/Semantic_error.mli
src/frontend/Typechecker.ml
test/integration/bad/function-signatures/overloading/stanc.expected
test/integration/bad/functions-bad8.stan
test/integration/bad/functions-bad9.stan
test/integration/bad/stanc.expected
test/stancjs/stancjs.expected

Improved the error generated when a function is re-declared, or when a function is not given a definition. 

Improve errors for function re-declaration or missing definition

---

src/frontend/Info.ml
test/integration/cli-args/info/info.expected
test/integration/cli-args/info/info.stan

This makes it so `print` and `reject` will now be listed as functions in `stanc --info`s output. The fact that these aren't technically functions but pseudo-compiler-builtins isn't something we really want to subject users to, IMO.
`print` and `reject` will now be listed as functions in `stanc --info`s output.

Add print and reject to info functions output

---

src/stan_math_backend/Statement_gen.ml
test/integration/good/code-gen/complex_numbers/cpp.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/mir.expected
test/integration/good/code-gen/mother.stan
test/integration/good/code-gen/transformed_mir.expected

Typechecker thinks that `reject()` and `print()` have the essentially the same signature but codegen differences mean that
* `print(vector)` outputs a comma-separated list of elements while `reject(vector)` uses tabs instead of commas
* `reject(array)` fails to compile
This pull request changes `reject()` codegen to behave more like `print()`
Fix using `reject()` with container types.

Fix reject() codegen for container types

---

Jenkinsfile

We have some problems with a plugin [perfReport](https://github.com/jenkinsci/performance-plugin) in Jenkins
Jenkins has been updated and the plugin has a [vulnerability](https://www.jenkins.io/security/advisory/2021-11-12/#SECURITY-2394) and has been disabled automatically.
We can't enable it back for security reasons therefore we have a few choices:
1. Comment out the plugin usage and if anyone misses it we can try building it from source and maintaining our own copy ( with the [vulnerability patched](https://github.com/jenkinsci/performance-plugin/pull/205) )
2. Build it from the source
3. Wait for updates (not really likely)
For now I talked with Brian and we decided the best way to go for now (mostly to un-stuck CI) is 1, we are waiting for Rok input too.
Hey …

Comment out perfReport usage until further updates of the plugin

---

src/frontend/Typechecker.ml
test/integration/good/code-gen/mir.expected
test/integration/good/code-gen/transformed_mir.expected
test/integration/good/compiler-optimizations/mem_patterns/transformed_mir.expected
test/integration/good/dataonly-int-return.stan
test/integration/good/pretty.expected

Fixes #803. This marks any function call which results in an integer as `data` rather than autodiffable. This will include things like `size`, `cols`, etc. 
Functions which return integer types are considered as "data" for purposes of data-only arguments. 

Treat int returns from functions as DataOnly

---

src/middle/Stan_math_signatures.ml
test/integration/bad/variadic_dae/bad_time0.stan
test/integration/bad/variadic_dae/bad_times_param.stan
test/integration/bad/variadic_dae/stanc.expected

Marked the `initial_time` and `times` parameters of the `dae` functions as DataOnly. If you look in the C++, they're `double`s:  https://github.com/stan-dev/math/blob/f4c68170c1f1e9bc1284520560204ea9e76c62cd/stan/math/rev/functor/dae.hpp#L167-L168
This causes a C++ compilation error which we should be catching in stanc, see https://discourse.mc-stan.org/t/compilation-error-on-using-the-differential-algebraic-equation-dae-solver-on-time-that-depends-on-the-parameters/29404
I'm going to ping @yizhang-yiz on this as the original author to confirm this is correct.
@rok-cesnovar IMO we can merge this during the freeze, but it doesn't warrant an RC2 all on its own. 
Marked the `initial_time` and `times` parameters of the `dae` functions as `data`. 
By submitting this pull …

Mark dae time parameters as DataOnly

---

src/frontend/Preprocessor.ml
test/integration/included/dune
test/integration/included/stanc.expected

Improves the error shown when an `#include`d file cannot be found to list the paths it searched on.

Show specified include paths in missing include error

---

src/stan_math_backend/Cpp.ml
src/stan_math_backend/Lower_program.ml
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/complex_numbers/cpp.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/ode/cpp.expected
test/integration/good/code-gen/opencl/cpp.expected
test/integration/good/code-gen/profiling/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected
test/integration/good/compiler-optimizations/mem_patterns/cpp.expected

Follow on to #1233, fixes a mispelled type (`Initalizer` instead of `Initializer`) and formats it closer to how clang-format does

Code gen: Fix spelling of 'Initalizer', update formatting

---

src/middle/Stan_math_signatures.ml
test/integration/good/function-signatures/math/matrix/eigenvalues.stan
test/integration/good/function-signatures/math/matrix/eigenvectors.stan
test/integration/signatures/stan_math_signatures.t

Adds overloads to `eigenvalues` and `eigenvectors` which accept a complex matrix as input. From https://github.com/stan-dev/math/pull/2846

Expose complex overloads for eigendecomposition

---

Jenkinsfile

A [CI failure](https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FStanc3/detail/master/168/pipeline/) has been reported in which the ghr call was failing with the [following error](https://github.com/tcnksm/ghr/blob/master/cli.go#L197):
`Failed to set up ghr: repository owner name not found`
In order to ensure this will not randomly fail in the future, we are passing the `-u` flag pointing to our CI username [stan-buildbot](https://github.com/stan-buildbot).

Added -u flag to ghr call to avoid random ci failure.

---

Jenkinsfile

Reverts stan-dev/stanc3#1283
This appears to have broken uploads, which are now targetting `https://api.github.com/repos/stan-buildbot/stanc3/release` which does not exist

Revert "Added -u flag to ghr call to avoid random ci failure."

---

.github/workflows/binaries.yml

Update to remove Node 12 based actions due to warnings: https://github.com/stan-dev/stanc3/actions/runs/4379746524

Update GHA build for Node 12 deprecation

---

src/frontend/Promotion.ml

Follow on to #1292. This fixes the names of the arguments and adds a few extra checks which would have caught the bug there originally. 

Make Promotion.get_type_promotion_exn more robust to bad inputs

---

src/stan_math_backend/Cpp.ml
src/stan_math_backend/Lower_stmt.ml
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/lir.expected
test/integration/good/code-gen/ode/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected

When printing we currently just append a `\n` character, but this will not always cause the print to flush.

Use std::endl to flush Stan prints

---

src/middle/Location.ml
src/middle/Location_span.ml

I have been playing around with profiling using [Landmarks](https://github.com/LexiFi/landmarks) and I found something kind of surprising: `Location.of_position_opt` is currently a pretty massive time waster in the compiler.
Of the ~78 million clock cycles spent in `Parse.parse_file` for the model I was benchmarking against, ~66 million of them are _just_ calling `Location.of_position_opt`, because basically every token wants to turn a `Lexing.position` into a `Location_span.t`. And, we're using an unnecessary and slow regex search in every one of those calls.
This re-writes that function to no-longer need to do a regex search. This changes the profiler output (name; location; calls; cycles) from
```
Location.of_position_opt; src/middle/Location.ml:122; 941; 66.38M
```
to
``` …
```

Speed up Location.of_position_opt

---

src/analysis_and_optimization/Debug_data_generation.ml
src/analysis_and_optimization/Debug_data_generation.mli
src/frontend/Ast_to_Mir.ml
src/frontend/Ast_to_Mir.mli
src/stanc/stanc.ml
src/stancjs/stancjs.ml
test/integration/cli-args/canonicalize/canonicalize.t
test/integration/cli-args/stanc.t
test/unit/Debug_data_generation_tests.ml

Adds a `--debug-generate-inits` flag to stanc which behaves like `--debug-generate-data` but for declarations in the `parameters` block.
This is useful for debugging in issues such as #1304 

Add ability to generate mock initial values, mirrors debug-generate-data

---

src/analysis_and_optimization/Optimize.ml
src/frontend/Ast_to_Mir.ml
src/middle/Internal_fun.ml
src/middle/Program.ml
src/middle/SizedType.ml
src/stan_math_backend/Lower_expr.ml
src/stan_math_backend/Lower_program.ml
src/stan_math_backend/Transform_Mir.ml
test/integration/cli-args/allow-undefined/cpp.expected
test/integration/cli-args/filename-in-msg/filename_good.expected
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/complex_numbers/cpp.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/lir.expected
test/integration/good/code-gen/mir.expected
test/integration/good/code-gen/ode/cpp.expected
test/integration/good/code-gen/opencl/cpp.expected
test/integration/good/code-gen/profiling/cpp.expected
test/integration/good/code-gen/profiling/transformed_mir.expected
test/integration/good/code-gen/transformed_mir.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected
test/integration/good/compiler-optimizations/mem_patterns/cpp.expected
test/integration/good/compiler-optimizations/mem_patterns/transformed_mir.expected
test/unit/Optimize.ml

Closes #1304.
This PR does a couple things:
1. Re-using the code gen we already have for the constructor, `transform_inits_impl` now takes in a var_context directly. This is what fixes #1304, and also will help out with #1100. The previous behavior of flattening it down to a flat vector was hacky, and for complex numbers or tuples, wrong.
2. Adds a new function called `unconstrain_array` which looks much more like the former `transform_inits`. This is the twin of `write_array` and can be eventually exposed/used in place of a lot of the places we're creating a `array_var_context`. The idea for a signature like this dates back to when the deserializer was added: https://github.com/stan-dev/stan/pull/3013#issuecomment-795906563. I added this here to keep the existing code for …

Update generated `transform_inits_impl` to directly accept a var_context.

---

src/frontend/SignatureMismatch.ml
src/middle/UnsizedType.ml
test/integration/bad/lang/stanc.expected
test/integration/bad/stanc.expected

When typecheck fails for an overloaded Stan Math function, the five signatures listed aren't always the most relevant ones. This PR changes the error sorting heuristic to prefer the types that have a similar shape to the one supplied by the user. See `bernoulli_logit` in the tests for an example of how it looks.

sort type errors by comparing to input type

---

src/stan_math_backend/Lower_functions.ml
test/integration/cli-args/allow-undefined/standalone-cpp.expected
test/integration/good/code-gen/standalone_functions/basic.stan
test/integration/good/code-gen/standalone_functions/cpp.expected
test/stancjs/standalone-functions.js

Closes #1312 
`--standalone-functions` now generates signatures which have the return type written out in full, rather than using `auto`.

Use full return type in --standalone-functions definitions

---

src/frontend/Typechecker.ml
src/stan_math_backend/Cpp.ml
test/integration/good/code-gen/mir.expected
test/integration/good/code-gen/profiling/transformed_mir.expected
test/integration/good/code-gen/transformed_mir.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/mem_patterns/transformed_mir.expected
test/integration/good/promotion/pretty.expected
test/integration/good/promotion/tilde_syntax.stan
test/unit/Factor_graph.ml

Closes #1337 
Fixed a bug with type promotion in the arguments to user-defined distributions generating bad C++.

Promote arguments of tilde statements properly

---

src/frontend/Typechecker.ml
src/frontend/parser.messages
src/frontend/parser.mly
test/integration/bad/compound-assign/stanc.expected
test/integration/bad/lang/bad_decl1.stan
test/integration/bad/lang/bad_decl4.stan
test/integration/bad/lang/stanc.expected
test/integration/bad/new/fundef-bad2.stan
test/integration/bad/new/stanc.expected
test/integration/bad/profiling/stanc.expected
test/integration/bad/reserved/stanc.expected
test/integration/bad/stanc.expected
test/integration/bad/tuples/incomplete3.stan
test/integration/bad/tuples/stanc.expected

See: https://discourse.mc-stan.org/t/ill-formed-phrase-should-be-followed-by-a-statement-variable-declaration-or-expression/32400
This reverts some portions of #771, but rather than using the UNREACHABLE token and updating the messages file, we simply raise the error ourselves directly. 
This unfortunately does make some errors worse, since continuing parsing let us do things like an informative error when a user writes `real foo, int bar;` to try to declare multiple variables of different types on one line. The slightly worse error in that case seems worth it compared to very confusing errors like in the linked thread. 
Improved errors when using a reserved word as a variable name.
license the submitted …

Stop reserved words in parser to prevent worse parse errors later

---

src/middle/Stan_math_signatures.ml
test/integration/good/function-signatures/math/matrix/complex_schur_decompose.stan
test/integration/good/function-signatures/math/matrix/csr_extract.stan
test/integration/good/function-signatures/math/matrix/eigendecompose.stan
test/integration/good/function-signatures/math/matrix/eigendecompose_sym.stan
test/integration/good/function-signatures/math/matrix/qr_thin.stan
test/integration/good/function-signatures/math/matrix/svd.stan
test/integration/signatures/stan_math_signatures.t

Counterpart to https://github.com/stan-dev/math/pull/2931
Exposed new functions `qr_thin`,  `eigendecompose_sym`, `eigendecompose`, `complex_schur_decompose`, `svd`, and `csr_extract`.

Add tuple-returning special functions

---

Jenkinsfile
docs/dependencies.mld
scripts/install_build_deps.sh
scripts/install_js_deps.sh
src/stancjs/dune

This bumps us from 3.11 to 4.1, which includes a fix for an inlining issue that can affect performance that @andrjohns found discussions of. Some quick local tests suggested that this is about 10% faster just from updating.
@serban-nicusor-toptal - I think to actually get this going in our CI we need to re-build our docker images, right?
Updated the OCaml-to-JS compiler used to create stanc.js

Update js_of_ocaml to 4.1.0

---

Jenkinsfile

Add jenkins configuration to remove old build logs and artifacts after some time to avoid running out of disk space. Feel free to tweak the specific numbers, as long as we don't keep them forever.

jenkins: remove old build logs

---

Jenkinsfile

Currently when jenkins runs `compare-compilers.sh` and `compare-optimizer.sh`, they end up running `runPerformanceTest.py` with no `-j` argument, so the resulting builds end up running `-j80` or something (from number of CPUs), while in fact they only have access to 4 cores (as set with `PARALLEL` in jenkins env).  As such the builds are running quite slowly. This should hopefully help.

jenkins: pass appropriate parallel arg to runPerformanceTests.py

---

scripts/docker/static/Dockerfile

Always pull latest version of containers-common and skopeo to avoid manually maintaining them.

Always pull latest version of containers-common and skopeo in Jenkins

---

src/middle/Stan_math_signatures.ml
test/integration/good/function-signatures/distributions/multivariate/discrete/dirichlet_multinomial/dirichlet_multinomial_lpmf.stan
test/integration/good/function-signatures/distributions/rngs.stan
test/integration/signatures/stan_math_distributions.t
test/integration/signatures/stan_math_signatures.t

In a [recent PR](https://github.com/stan-dev/math/pull/2979), I added the Dirichlet-multinomial distribution to the Stan Math library. This PR exposes the distribution to the user.
Added the `dirichlet_multinomial` distribution.

Exposed the dirichlet_multinomial distribution

---

.github/workflows/binaries.yml

Reported by @yizhang-yiz - recent versions of dune do not build with the older MacOS SDK we use, so we pin an older version.

Fix "build binaries" action on MacOS

---

src/stan_math_backend/Lower_functions.ml
src/stan_math_backend/Lower_program.ml
test/integration/cli-args/allow-undefined/cpp.expected
test/integration/cli-args/filename-in-msg/filename_good.expected
test/integration/good/code-gen/cl.expected
test/integration/good/code-gen/complex_numbers/cpp.expected
test/integration/good/code-gen/cpp.expected
test/integration/good/code-gen/expressions/cpp.expected
test/integration/good/code-gen/lir.expected
test/integration/good/code-gen/ode/cpp.expected
test/integration/good/code-gen/opencl/cpp.expected
test/integration/good/code-gen/profiling/cpp.expected
test/integration/good/code-gen/standalone_functions/cpp.expected
test/integration/good/compiler-optimizations/cpp.expected
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected
test/integration/good/compiler-optimizations/mem_patterns/cpp.expected
test/integration/good/tuples/cpp.expected

Follow on to https://github.com/stan-dev/stan/pull/3263. The generated C++ no longer assumes that the RNG used in Stan is specifically the `boost::ecuyer1988` generator, but uses a type alias defined in the Stan library.

Avoid hardcoding boost::ecuyer1988

---

src/middle/Location.ml
test/stancjs/stancjs.expected

On error, stanc prints the problematic source line and a caret that points to the horizontal location of the error but if the source line contains tabs instead of spaces the caret was at the wrong location.
A simple fix is to duplicate the tabs from the source to the line that contains the caret.

use tabs to position error message cursor when appropriate

---

src/frontend/Deprecation_analysis.ml
test/integration/good/warning/pretty.expected

Replaced the link show when the deprecated `lkj_cov` distribution is used with the new link (see https://github.com/stan-dev/docs/pull/694).

Emit new link for lkj_cov deprecation

---

src/common/ICE.ml
src/stanc/stanc.ml
src/stancjs/stancjs.ml
test/unit/Error_tests.ml

This closes #1408. There is no real difference in the end result for the binary executable, but this is a huge improvement for stanc3js since internal errors will be cleanly converted to the error string format rather than percolating as javascript exceptions.
The compiler should display a cleaner error if it encounters an internal error.

Improve internal error handling and message

---

Jenkinsfile
scripts/docker/publish/Dockerfile

Requested in #1418, this will replace the `ghr` binary with the official `gh` binary from Github.

[CI] Switch to gh binary for releases

---

src/stan_math_backend/Lower_expr.ml
test/integration/good/code-gen/complex_numbers/basic_op_param.stan
test/integration/good/code-gen/complex_numbers/basic_operations.stan
test/integration/good/code-gen/complex_numbers/basic_ops_mix.stan
test/integration/good/code-gen/complex_numbers/cpp.expected

Fixed an issue where `operator/` was not generating the correct C++ for complex linear algebra types.

Fix complex matrix division miscompilation

---

docs/dependencies.mld
scripts/docker/debian/Dockerfile
scripts/install_js_deps.sh

Closes #1425
Rollback js_of_ocaml to 5.4.0 for compatibility with QuickJS

Rollback JSOO version for QuickJS compatibility

---

src/analysis_and_optimization/Pedantic_analysis.ml
test/integration/cli-args/warn-pedantic/stanc.expected

Updated pedantic mode warning for jacobian usage to mention `jacobian +=`

Update pedantic mode warning for jacobian usage

---

.github/workflows/binaries.yml

The build-binaries github action had broken on the newer macOS runners that use arm64. It's probably worth fixing eventually, but for now the easiest thing is just to use an older runner.
See test run here: https://github.com/WardBrian/stanc3/actions/runs/11239798252

Keep github actions build on x86 mac for now

---

.github/workflows/binaries.yml
Jenkinsfile
scripts/hooks/pre-commit

The MacOS binaries we distribute are now 'universal' (fat) binaries, and therefore will not require Rosetta to run.

Build 'universal' binaries on MacOS

---

docs/dependencies.mld
scripts/docker/debian/Dockerfile
scripts/install_js_deps.sh

Ref. 
https://github.com/stan-dev/stanc3/issues/1425
https://github.com/quickjs-ng/quickjs/issues/741
https://github.com/andrjohns/QuickJSR/issues/76
Bumped JS-of-Ocaml version to 5.9.1

Bump JSOO to 5.9.1 following quickjs fixes

---

test/integration/cli-args/debug-generation.t/run.t
test/integration/cli-args/output-files.t/run.t
test/integration/cli-args/stanc.t

This makes the tests a bit easier to read and has some nice benefits like preserving error codes rather than them being swallowed by pipes. 
- x ] Run unit tests

Update formatting of Cram tests

---

src/frontend/Errors.ml
src/frontend/Errors.mli
src/frontend/Pretty_print_prog.ml
src/stanc/CLI.ml
src/stanc/stanc.ml
test/integration/cli-args/stanc.t
test/unit/In_memory_include_tests.ml
test/unit/Parse_tests.ml
test/unit/Test_utils.ml

This is a small change that allows some better 'scriptability' of the compiler, e.g.
```
$ cat test/integration/good/for_early_return.stan | stanc - --auto-format
functions {
real ends() {
for (i in 1 : 10) {
return 1;
}
}
}
transformed parameters {
real a = ends();
}
```
The compiler now accepts `-` as a model argument, in which case it reads from standard input

Allow model to be supplied on stdin with '-'

---

src/analysis_and_optimization/Dataflow_types.ml
src/analysis_and_optimization/Factor_graph.ml
src/analysis_and_optimization/dune
src/common/dune
src/driver/dune
src/frontend/Ast_to_Mir.ml
src/frontend/Environment.ml
src/frontend/SignatureMismatch.ml
src/frontend/Typechecker.ml
src/frontend/dune
src/middle/dune
src/stan_math_backend/Cpp_Json.ml
src/stan_math_backend/Mangle.ml
src/stan_math_backend/Transform_Mir.ml
src/stan_math_backend/dune
src/stanc/dune
src/stancjs/dune
test/unit/Error_tests.ml
test/unit/dune

This started with me testing building the compiler under OCaml 5.3.0. After installing the most recent version of our dependencies, the build was still failing, because `re` wasn't installed. It turns out, it's no longer in the Jane Street dependency tree in the next version (0.17.x)
I then realized we were not documenting this dependency anywhere, and it's also completely unnecessary based on its usages. So I pulled it out, and then updated the dune files to not request linking it. It turns out that the `str` library we were listing was also just requesting a link to our own alias of `module Str = Re.Str`, which was... messy, to say the least!
Removed usages of the `re` library
license the submitted …

Remove usages of re, clean up libraries fields in dune

---

src/driver/Entry.ml
src/stanc/stanc.ml
test/integration/cli-args/model-name/stanc.t
test/stancjs/model_name.js
test/stancjs/stancjs.expected

Fixes #1491 where repeated calls to stanc.js would re-use the same model namespace in the generated C++

Restore previous behavior of model name arguments

---

Jenkinsfile

This PR adds a step to the Jenkinsfile stage for nightly releases to also update `rstan`'s bundled `stanc.js`.
@serban-nicusor-toptal would you be able to check whether I've specified the credentials/config correctly? Thanks!
Update `develop` rstan on nightly release of new `stanc.js`

Update rstan's stanc.js on nightly release

---

src/analysis_and_optimization/Memory_patterns.ml
src/frontend/Environment.ml
src/frontend/Typechecker.ml
src/middle/Stan_math_signatures.ml
src/middle/Stan_math_signatures.mli
src/stan_math_backend/Lower_expr.ml

This is a small change that tries to encapsulate more. In theory we could even use something other than a hash map now, including something that does computation (which could be one solution to #1373, though I'm not necessarily advocating for it)

Stop directly exposing hashmaps from Stan_math_signatures

---

src/frontend/Typechecker.ml
test/integration/bad/embedded_laplace/autodiff_incompatibility5.stan
test/integration/bad/embedded_laplace/stanc.expected

Follow on to #1513. I realized that when combined with really esoteric functions like `int_step` or the size functions, one might be able to smuggle higher-order-incompatible functions into the expression of an lvalue index, which we were not previously checking. 
Note that I could not actually get an example where the C++ failed to compile after a couple tries, but it seems best to prevent these anyway for now.

Laplace: also check into index expressions for incompatibilities. 

---

.github/workflows/binaries.yml
Jenkinsfile
Jenkinsfile-test-binaries

Older dunes are no longer available on the normal opam repository, c.f. https://github.com/ocaml/opam-repository/issues/28065

Add opam archive for older Dune version

---

.github/workflows/binaries.yml

Required due to underlying changes to the runner-images. See https://github.com/stan-dev/stanc3/actions/runs/16502365070 for a passing example

Fix cross-windows build in Github Actions

---

src/stan_math_signatures/Generate.ml
test/integration/good/compiler-optimizations/cppO0.expected
test/integration/good/compiler-optimizations/cppO1.expected
test/integration/good/compiler-optimizations/initialize-SoA.stan

See https://github.com/stan-dev/math/pull/3221#issuecomment-3191808781
Fixed a few functions being labeled as supporting the struct-of-arrays matrix type when they in fact did not. 

Fix some scalar functions being mislabeled as SoA

---

src/frontend/Errors.ml
src/frontend/Errors.mli
src/frontend/Parse.ml
src/frontend/Preprocessor.ml
src/frontend/Preprocessor.mli
src/frontend/Syntax_error.ml
src/frontend/Syntax_error.mli
src/frontend/Typechecker.ml
src/frontend/Typechecker.mli
src/frontend/lexer.mll
src/frontend/parser.mly
src/middle/Location_span.ml
test/integration/bad/lang/stanc.expected
test/integration/bad/new/stanc.expected
test/integration/bad/numeric-literal/stanc.expected
test/integration/bad/removed_features/stanc.expected
test/integration/bad/stanc.expected
test/integration/bad/tuples/stanc.expected
test/integration/included/stanc.expected
test/stancjs/stancjs.expected
test/unit/In_memory_include_tests.ml

There are a couple places where we use exceptions for control flow. This PR improves the encapsulation of those usages by making the exception type module-local and private, preventing other modules from throwing these, or even knowing that they are being used.  
This required a little bit of module trickery for the parsing code, but I don't think it's too bad overall.

Encapsulate local exception usage

---

src/stancjs/dune

Because stanc.js doesn't do any filesystem loading or other features, we can make it slightly more compatible by passing `--target=browser`. This only changes what the code tries to import, not how downstream users can use it (e.g., it will still work with node)
stanc3js will no longer try to load node modules at startup

JS Build: Don't try to load node modules
